import Link from 'next/link';
import { ArrowRight, BadgeCheck, CircleDot, FileCheck2, Radar, Sparkles, UserRoundCheck } from 'lucide-react';
import { MittoCareerShell } from '@/components/careers/MittoCareerShell';
import { GlassCard, SectionHeading, StatusBadge } from '@/components/careers/MittoPrimitives';
import { mittoFeatures, mittoJourney } from '@/components/careers/mitto-career-data';
import { listPublicCareerPackages } from '@/server/careers/packages';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Mitto Career | Managed job-search command center', description: 'Human-reviewed career automation from résumé intake to application preparation.' };

export default async function CareersLandingPage() {
  const configured = await listPublicCareerPackages('INR');
  const packages = configured.length ? configured : fallbackPackages;
  return <MittoCareerShell>
    <section className="mx-auto grid max-w-[1480px] gap-14 px-5 pb-24 pt-16 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-32 lg:pt-24">
      <div className="flex flex-col justify-center">
        <div className="flex w-fit items-center gap-2 rounded-full border border-cyan-300/15 bg-cyan-300/8 px-3 py-1.5 text-xs font-semibold text-cyan-100"><Sparkles className="size-3.5" /> Managed career automation · approval first</div>
        <h1 className="mt-8 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[5.6rem]">Your managed job-search <span className="bg-gradient-to-r from-cyan-200 via-white to-violet-300 bg-clip-text text-transparent">command center.</span></h1>
        <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">Mitto Career moves international candidates from résumé upload to job discovery, application preparation, human review, and interview tracking—with every step visible in one calm workspace.</p>
        <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/careers/onboarding" className="mitto-button inline-flex items-center justify-center gap-2 px-5 py-3">Start your career journey <ArrowRight className="size-4" /></Link><Link href="/careers/demo" className="mitto-button-secondary px-5 py-3">View live demo</Link></div>
        <div className="mt-10 flex flex-wrap gap-x-5 gap-y-3">{['Human-reviewed outputs','No auto-apply without approval','Résumé + job-fit analysis','Europe launch corridor'].map(item => <span key={item} className="flex items-center gap-2 text-xs text-slate-400"><BadgeCheck className="size-3.5 text-emerald-300" />{item}</span>)}</div>
      </div>
      <CommandCenterPreview />
    </section>
    <section id="journey" className="mx-auto max-w-[1480px] px-5 py-24 lg:px-8"><SectionHeading eyebrow="One clear journey" title="From profile to progress, without the black box." copy="Five understandable stages replace scattered portals, spreadsheets, and uncertain handoffs." /><div className="mt-12 grid gap-3 lg:grid-cols-5">{mittoJourney.map(([title, detail], i) => <GlassCard key={title} className="p-5 transition duration-300 hover:-translate-y-1 hover:border-cyan-300/25"><div className="flex size-9 items-center justify-center rounded-xl bg-white/7 text-xs font-bold text-cyan-200">0{i+1}</div><h3 className="mt-7 font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{detail}</p></GlassCard>)}</div></section>
    <section className="border-y border-white/7 bg-white/[.018]"><div className="mx-auto max-w-[1480px] px-5 py-24 lg:px-8"><SectionHeading eyebrow="Capability map" title="A real workflow, honestly labeled." copy="See what is available, demo-safe, feature-gated, and next—before you commit." /><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{mittoFeatures.map(feature => <GlassCard key={feature.title} className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex size-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-300/15 to-violet-400/15 text-cyan-100"><CircleDot className="size-4" /></div><StatusBadge status={feature.status} /></div><h3 className="mt-5 font-semibold">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{feature.detail}</p></GlassCard>)}</div></div></section>
    <section id="packages" className="mx-auto max-w-[1480px] px-5 py-24 lg:px-8"><SectionHeading eyebrow="Managed service" title="Choose the support level. Keep the visibility." copy="Every package uses the same human-reviewed foundation." /><div className="mt-12 grid gap-4 lg:grid-cols-3">{packages.slice(0,3).map((pkg,index)=><GlassCard key={pkg.code} className={`p-6 ${index===1?'border-cyan-300/30 bg-cyan-300/[.07]':''}`}><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-200">{index===1?'Most guided':'Managed plan'}</p><h3 className="mt-4 text-2xl font-semibold">{pkg.name}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-slate-400">{pkg.description}</p><div className="my-6 h-px bg-white/8" />{(pkg.features||[]).slice(0,4).map(feature=><p key={feature} className="mt-3 flex gap-2 text-sm text-slate-300"><BadgeCheck className="mt-0.5 size-4 shrink-0 text-emerald-300" />{feature}</p>)}<Link href="/careers/onboarding" className="mitto-button-secondary mt-7 w-full">Select and continue <ArrowRight className="size-4" /></Link></GlassCard>)}</div></section>
  </MittoCareerShell>;
}

function CommandCenterPreview(){return <div className="mitto-float relative lg:pl-8"><GlassCard className="p-3"><div className="rounded-[1.15rem] border border-white/8 bg-[#0b0e19]/90 p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-slate-500">Candidate workspace</p><p className="mt-1 font-semibold">Europe search · active</p></div><span className="rounded-full bg-emerald-300/10 px-2.5 py-1 text-[10px] font-semibold text-emerald-200">Human reviewed</span></div><div className="mt-6 grid grid-cols-3 gap-3">{[['84%','Profile'],['48','Jobs found'],['6','Shortlisted']].map(([value,label])=><div key={label} className="rounded-2xl border border-white/8 bg-white/[.045] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-white/8 bg-white/[.045] p-4"><div className="flex items-center gap-2 text-sm font-medium"><Radar className="size-4 text-cyan-200"/>Journey</div><div className="mt-5 space-y-4">{['Workspace prepared','Application kit','Human review'].map((label,i)=><div key={label} className="flex items-center gap-3"><span className={`size-2 rounded-full ${i<2?'bg-emerald-300':'bg-amber-300'}`}/><div className="h-1.5 flex-1 rounded-full bg-white/8"><div className={`h-full rounded-full ${i<2?'w-full bg-emerald-300/60':'w-2/3 bg-amber-300/60'}`}/></div><span className="text-[11px] text-slate-400">{label}</span></div>)}</div></div><div className="grid gap-3"><Mini icon={FileCheck2} title="Application kit" status="Ready for review"/><Mini icon={UserRoundCheck} title="Reviewer" status="Approval pending"/></div></div></div></GlassCard></div>}
function Mini({icon:Icon,title,status}:{icon:typeof FileCheck2;title:string;status:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.045] p-4"><Icon className="size-4 text-violet-200"/><p className="mt-3 text-xs font-medium">{title}</p><p className="mt-1 text-[10px] text-slate-500">{status}</p></div>}
const fallbackPackages=[{code:'MITTO_START',name:'Mitto Start',description:'Structured intake, résumé setup, and dashboard visibility.',features:['Candidate onboarding','Résumé intake','Profile intelligence','Progress dashboard']},{code:'MITTO_GUIDED',name:'Mitto Guided',description:'Deeper managed support with discovery and application-kit review.',features:['Everything in Start','Job discovery workflow','Application-kit preview','Human review queue']},{code:'MITTO_PLUS',name:'Mitto Plus',description:'Our most hands-on managed workflow for complex international searches.',features:['Everything in Guided','Priority operations review','Sponsorship signal review','Employer-response readiness']}];
