import type { VisaApplication, WalletTransaction, VisaType, AllianceLink, OverstayCase } from '@/types';

export const mockAgency = {
  id: 'agency-001',
  name: 'Vindox Travels',
  email: 'vindoxservices@gmail.com',
  phone: '+918553094349',
  country: 'India',
  accountType: 'b2b',
  gstNumber: '29AABCV1234F1ZG',
  panCard: 'AABCV1234F',
  addressLine1: 'No 42, 3rd Cross, Jayanagar 4th Block',
  addressLine2: 'Near Metro Station',
  city: 'Bangalore',
  state: 'Karnataka',
  zipCode: '560103',
  walletBalance: 28040,
};

export const mockVisaTypes: VisaType[] = [
  {
    id: 'visa-001',
    destination: 'Vietnam',
    name: 'Lightning Fast Visa (6 Business Hours)',
    category: 'LIGHTNING_FAST',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '6 Business Hours',
    price: 8999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary'],
    cutoffTime: '11:30 AM',
  },
  {
    id: 'visa-002',
    destination: 'Vietnam',
    name: 'Evisa Vietnam 30 Days',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 2700,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-003',
    destination: 'Vietnam',
    name: 'Vietnam 90 Days Multiple Entry E-Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 12404,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },
  {
    id: 'visa-004',
    destination: 'UAE',
    name: 'UAE 30 Days Single Entry Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 6499,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-005',
    destination: 'UAE',
    name: 'UAE 60 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '60 days',
    duration: '60 days',
    processingTime: '5-7 Business Days',
    price: 14599,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement'],
  },
  {
    id: 'visa-006',
    destination: 'Singapore',
    name: 'Singapore Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter'],
  },
  {
    id: 'visa-007',
    destination: 'Australia',
    name: 'Australia Visitors Visa (Subclass 600)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '12 months',
    duration: '3 months per entry',
    processingTime: '15-20 Business Days',
    price: 13499,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'National ID', 'ITR', 'Bank Statement', 'Salary Slips', 'Covering Letter', 'Form 54'],
  },
  {
    id: 'visa-008',
    destination: 'Thailand',
    name: 'Thailand Tourist Visa (60 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '60 days',
    duration: '60 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },
];

const createTraveler = (overrides: Partial<import('@/types').Traveler> & { id: string; firstName: string; lastName: string; passportNumber: string }): import('@/types').Traveler => ({
  nationality: 'Indian',
  sex: 'Male',
  dateOfBirth: '1990-05-15',
  placeOfBirth: 'Bangalore',
  placeOfIssue: 'Bangalore',
  maritalStatus: 'Single',
  dateOfIssue: '2023-01-10',
  dateOfExpiry: '2033-01-09',
  isChild: false,
  status: 'APPROVED',
  referenceNo: `E260308INDR${overrides.passportNumber.slice(-6)}`,
  estimatedArrival: '2026-03-13',
  deliveredAt: '2026-03-12',
  ...overrides,
});

export const mockApplications: VisaApplication[] = [
  {
    id: 'app-001',
    agencyId: 'agency-001',
    groupId: 'grp-001',
    internalId: 'C7612934',
    groupName: 'SAPNA CHHAJER',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-24',
    returnDate: '2026-04-07',
    status: 'APPROVED',
    totalPrice: 21600,
    createdAt: '2026-03-07T18:43:00',
    updatedAt: '2026-03-12T10:00:00',
    travelers: [
      createTraveler({ id: 't-001', firstName: 'Hiyansh Amit', lastName: 'Chhajer', passportNumber: 'C7819328', isChild: true, dateOfBirth: '2018-08-22' }),
      createTraveler({ id: 't-002', firstName: 'Pratiksha', lastName: 'Jain', passportNumber: 'J7820156', sex: 'Female' }),
      createTraveler({ id: 't-003', firstName: 'Mukesh', lastName: 'Kumar', passportNumber: 'K8234512' }),
      createTraveler({ id: 't-004', firstName: 'Sapna', lastName: 'Chhajer', passportNumber: 'C7612934', sex: 'Female' }),
      createTraveler({ id: 't-005', firstName: 'Hiyanshi Amit', lastName: 'Chhajer', passportNumber: 'C7612935', isChild: true, dateOfBirth: '2020-03-15' }),
      createTraveler({ id: 't-006', firstName: 'Manya', lastName: 'Bohra', passportNumber: 'B6123456', isChild: true, dateOfBirth: '2019-11-08' }),
      createTraveler({ id: 't-007', firstName: 'Purvansh', lastName: 'Bohra', passportNumber: 'B6123457', isChild: true, dateOfBirth: '2021-06-20' }),
      createTraveler({ id: 't-008', firstName: 'Livi', lastName: 'Chhajer', passportNumber: 'C7612936', isChild: true, dateOfBirth: '2022-01-12' }),
    ],
  },
  {
    id: 'app-002',
    agencyId: 'agency-001',
    groupId: 'grp-002',
    internalId: 'G4521987',
    groupName: 'VISHAL GIREEYA',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-20',
    returnDate: '2026-04-03',
    status: 'APPROVED',
    totalPrice: 10800,
    createdAt: '2026-03-05T14:20:00',
    updatedAt: '2026-03-10T09:30:00',
    travelers: [
      createTraveler({ id: 't-009', firstName: 'Vishal', lastName: 'Gireeya', passportNumber: 'G4521987' }),
      createTraveler({ id: 't-010', firstName: 'Priya', lastName: 'Gireeya', passportNumber: 'G4521988', sex: 'Female' }),
      createTraveler({ id: 't-011', firstName: 'Arjun', lastName: 'Gireeya', passportNumber: 'G4521989', isChild: true, dateOfBirth: '2017-09-14' }),
      createTraveler({ id: 't-012', firstName: 'Meera', lastName: 'Gireeya', passportNumber: 'G4521990', isChild: true, dateOfBirth: '2020-04-25' }),
    ],
  },
  {
    id: 'app-003',
    agencyId: 'agency-001',
    groupId: 'grp-003',
    internalId: 'J6789012',
    groupName: 'KAUSHIK JAIN',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-04-01',
    returnDate: '2026-04-15',
    status: 'PAYMENT_PENDING',
    totalPrice: 5400,
    createdAt: '2026-03-10T11:00:00',
    updatedAt: '2026-03-10T11:00:00',
    travelers: [
      createTraveler({ id: 't-013', firstName: 'Kaushik', lastName: 'Jain', passportNumber: 'J6789012', status: 'PAYMENT_PENDING' }),
      createTraveler({ id: 't-014', firstName: 'Ritu', lastName: 'Jain', passportNumber: 'J6789013', sex: 'Female', status: 'PAYMENT_PENDING' }),
    ],
  },
  {
    id: 'app-004',
    agencyId: 'agency-001',
    groupName: 'AKASH KOTHARI',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-02-26',
    returnDate: '2026-03-12',
    status: 'APPROVED',
    totalPrice: 2700,
    createdAt: '2026-03-06T13:46:00',
    updatedAt: '2026-03-12T10:00:00',
    travelers: [
      createTraveler({ id: 't-015', firstName: 'Akash', lastName: 'Kothari', passportNumber: 'R1213598', referenceNo: 'E260308INDR121359397', estimatedArrival: '2026-03-13', deliveredAt: '2026-03-12' }),
    ],
  },
  {
    id: 'app-005',
    agencyId: 'agency-001',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-01',
    returnDate: '2026-03-15',
    status: 'APPROVED',
    totalPrice: 2700,
    createdAt: '2026-02-25T09:15:00',
    updatedAt: '2026-03-08T14:00:00',
    travelers: [
      createTraveler({ id: 't-016', firstName: 'Nisarga', lastName: 'Shavahalli Prakash', passportNumber: 'N9876543', referenceNo: 'E260308INDN987654321', estimatedArrival: '2026-03-05', deliveredAt: '2026-03-04' }),
    ],
  },
  {
    id: 'app-006',
    agencyId: 'agency-001',
    groupId: 'grp-004',
    internalId: 'M1234567',
    groupName: 'RAHUL SHARMA',
    destination: 'UAE',
    visaType: 'UAE 30 Days Single Entry Visa',
    visaCategory: 'STANDARD',
    travelDate: '2026-04-10',
    returnDate: '2026-05-10',
    status: 'SUBMITTED',
    totalPrice: 19497,
    createdAt: '2026-03-15T16:30:00',
    updatedAt: '2026-03-16T08:00:00',
    travelers: [
      createTraveler({ id: 't-017', firstName: 'Rahul', lastName: 'Sharma', passportNumber: 'M1234567', status: 'SUBMITTED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-018', firstName: 'Anita', lastName: 'Sharma', passportNumber: 'M1234568', sex: 'Female', status: 'SUBMITTED' }),
      createTraveler({ id: 't-019', firstName: 'Vikram', lastName: 'Sharma', passportNumber: 'M1234569', status: 'SUBMITTED' }),
    ],
  },
];

export const mockTransactions: WalletTransaction[] = [
  { id: 'txn-001', type: 'DEPOSIT', amount: 50000, method: 'BANK_TRANSFER', status: 'COMPLETED', description: 'Bank Transfer - YES Bank', createdAt: '2026-03-01T10:00:00' },
  { id: 'txn-002', type: 'PAYMENT', amount: -21600, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Sapna Chhajer Group (8 travelers)', createdAt: '2026-03-07T18:45:00' },
  { id: 'txn-003', type: 'PAYMENT', amount: -10800, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Vishal Gireeya Group (4 travelers)', createdAt: '2026-03-05T14:25:00' },
  { id: 'txn-004', type: 'PAYMENT', amount: -2700, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Akash Kothari', createdAt: '2026-03-06T13:50:00' },
  { id: 'txn-005', type: 'PAYMENT', amount: -2700, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Nisarga Shavahalli Prakash', createdAt: '2026-02-25T09:20:00' },
  { id: 'txn-006', type: 'REFUND', amount: 500, method: 'WALLET', status: 'COMPLETED', description: 'Refund - Duplicate payment correction', createdAt: '2026-03-08T11:00:00' },
  { id: 'txn-007', type: 'DEPOSIT', amount: 25000, method: 'UPI', status: 'COMPLETED', description: 'UPI Deposit', createdAt: '2026-03-10T09:00:00' },
  { id: 'txn-008', type: 'PAYMENT', amount: -19497, method: 'WALLET', status: 'COMPLETED', description: 'UAE Visa - Rahul Sharma Group (3 travelers)', createdAt: '2026-03-15T16:35:00' },
  { id: 'txn-009', type: 'WITHDRAWAL', amount: -5403, method: 'BANK_TRANSFER', status: 'PENDING', description: 'Withdrawal to registered bank', createdAt: '2026-03-16T10:00:00' },
  { id: 'txn-010', type: 'DEPOSIT', amount: 10000, method: 'CREDIT_CARD', status: 'COMPLETED', description: 'Credit Card Deposit (2% fee: ₹200)', createdAt: '2026-03-12T14:30:00' },
];

export const mockAllianceLinks: AllianceLink[] = [];

export const mockOverstayCases: OverstayCase[] = [];

export const mockTestimonials = [
  { id: 1, company: 'Burnmiles', quote: 'VVisa has transformed how we handle visa applications. The bulk upload feature alone saves us 20+ hours every week. Our approval rate went from 85% to 99%.', author: 'Rajesh Mehta', role: 'Founder' },
  { id: 2, company: 'RV Holiday', quote: 'The wallet system and real-time tracking are game-changers. We can process 500+ applications in a single click. No other platform comes close.', author: 'Priya Iyer', role: 'Operations Head' },
  { id: 3, company: 'Jetways', quote: 'Switching to VVisa was the best decision we made. The 24/7 support and dedicated account manager make us feel like a priority client.', author: 'Amit Desai', role: 'Managing Director' },
  { id: 4, company: 'Family Holidays', quote: 'Our clients love the transparency. They can track their visa status in real-time. Our customer satisfaction scores have never been higher.', author: 'Sneha Kapoor', role: 'CEO' },
  { id: 5, company: 'Travozone', quote: 'Best prices in the market, hands down. The group application feature makes handling corporate travel seamless. Highly recommended for any B2B agency.', author: 'Karan Patel', role: 'Travel Director' },
];

export const mockFAQs = [
  { id: 1, question: 'What is ETA and How is it Calculated?', answer: 'ETA (Estimated Time of Arrival) is the projected date your visa will be approved and delivered. It is calculated based on the visa processing time for your selected category, the time of submission, and the destination country\'s embassy working hours. For example, our Lightning Fast visas submitted before 11:30 AM are typically processed within 6 business hours.' },
  { id: 2, question: 'Can I Track the Status of My Application?', answer: 'Yes! You can track every application in real-time from your dashboard. Each application goes through clear stages: Draft → Validated → Payment Pending → Paid → Submitted to Immigration → Approved. You\'ll also receive notifications for status changes via email and in-app alerts.' },
  { id: 3, question: 'Do You Provide Support After I Submit My Application?', answer: 'Absolutely. Our dedicated support team is available 24/7. Each agency is assigned a dedicated Account Manager who can be reached via phone, email, or in-app chat. We handle embassy follow-ups, document resubmissions, and any queries on your behalf.' },
  { id: 4, question: 'How Do I Make a Payment?', answer: 'We support three payment methods: Bank Transfer (0% fee), UPI (0% fee), and Credit Card (2% processing fee). Simply add funds to your VVisa Wallet, and all visa payments are automatically deducted when you submit applications. Deposits reflect within 30 minutes to 2 hours.' },
  { id: 5, question: 'Do I Get GST Invoices?', answer: 'Yes, you get GST-compliant invoices for every transaction. You can download invoices from the Applications page for each group or individual application. Ensure your GST certificate is uploaded in the Profile section to enable GST input credit.' },
  { id: 6, question: 'Do You Offer Support for Group Applications?', answer: 'Yes! Group applications are one of our core strengths. You can add up to 500 travelers in a single group application. Each traveler gets their own passport upload, document section, and status tracking. Group discounts are automatically applied for bulk applications.' },
];

export const popularDestinations = ['Vietnam', 'UAE', 'Singapore', 'Thailand', 'Australia', 'Malaysia', 'Turkey', 'Sri Lanka', 'Maldives', 'Indonesia'];

export const statusConfig: Record<string, { label: string; bg: string; text: string; dot: string }> = {
  APPROVED: { label: 'Approved', bg: 'bg-emerald-950/50', text: 'text-emerald-400', dot: 'bg-emerald-400' },
  REJECTED: { label: 'Rejected', bg: 'bg-red-950/50', text: 'text-red-400', dot: 'bg-red-400' },
  PAYMENT_PENDING: { label: 'Pending Payment', bg: 'bg-amber-950/50', text: 'text-amber-400', dot: 'bg-amber-400' },
  PENDING: { label: 'Pending', bg: 'bg-amber-950/50', text: 'text-amber-400', dot: 'bg-amber-400' },
  SUBMITTED: { label: 'Submitted', bg: 'bg-blue-950/50', text: 'text-blue-400', dot: 'bg-blue-400' },
  DRAFT: { label: 'Draft', bg: 'bg-gray-800/50', text: 'text-gray-400', dot: 'bg-gray-400' },
  RECEIVED: { label: 'Received', bg: 'bg-blue-950/50', text: 'text-blue-400', dot: 'bg-blue-400' },
  VALIDATED: { label: 'Validated', bg: 'bg-indigo-950/50', text: 'text-indigo-400', dot: 'bg-indigo-400' },
  QUEUED: { label: 'Queued', bg: 'bg-purple-950/50', text: 'text-purple-400', dot: 'bg-purple-400' },
  PAID: { label: 'Paid', bg: 'bg-emerald-950/50', text: 'text-emerald-400', dot: 'bg-emerald-400' },
  OTP_PENDING: { label: 'OTP Pending', bg: 'bg-amber-950/50', text: 'text-amber-400', dot: 'bg-amber-400' },
  FAILED: { label: 'Failed', bg: 'bg-red-950/50', text: 'text-red-400', dot: 'bg-red-400' },
  CANCELLED: { label: 'Cancelled', bg: 'bg-gray-800/50', text: 'text-gray-400', dot: 'bg-gray-400' },
};