import type {
  VisaApplication,
  WalletTransaction,
  VisaType,
  AllianceLink,
  OverstayCase,
  DashboardStats,
  VisaDocumentRequirement,
  VisaEntryType,
  VisaKind,
  VisaPricingLineItem,
} from '@/types';
import { buildVisaPriceBreakdown, rupeesToMinor } from '@/lib/pricing';

export const mockAgency = {
  id: 'agency-001',
  name: 'Vindox Travels',
  email: 'vindoxservices@gmail.com',
  phone: '+918553094349',
  country: 'India',
  accountType: 'b2b',
  gstNumber: '29AABCV1234F1ZG',
  panCard: 'AABCV1234F',
  addressLine1: 'No 42, 3rd Cross, Jayanagar 4th Block',
  addressLine2: 'Near Metro Station',
  city: 'Bangalore',
  state: 'Karnataka',
  zipCode: '560103',
  walletBalance: 28040,
};

const slugifyCatalogueId = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const inferVisaKind = (visa: Pick<VisaType, 'name'>): VisaKind => {
  const name = visa.name.toLowerCase();

  if (name.includes('eta')) return 'ETA';
  if (name.includes('arrival')) return 'VISA_ON_ARRIVAL';
  if (name.includes('evisa') || name.includes('e-visa') || name.includes('entri')) return 'E_VISA';
  if (name.includes('sticker') || name.includes('b1/b2') || name.includes('schengen')) return 'STICKER_VISA';

  return 'OTHER';
};

const inferEntryType = (entry: string): VisaEntryType => {
  const normalized = entry.toLowerCase();

  if (normalized.includes('multiple')) return 'MULTIPLE';
  if (normalized.includes('double')) return 'DOUBLE';
  if (normalized.includes('single')) return 'SINGLE';

  return 'NOT_SPECIFIED';
};

const buildDocumentRequirements = (visa: Pick<VisaType, 'id' | 'documents'>, visaKind: VisaKind) => {
  const mandatory: VisaDocumentRequirement[] = visa.documents.map((documentName) => ({
    id: `${visa.id}-${slugifyCatalogueId(documentName)}`,
    label: documentName,
    documentCode: slugifyCatalogueId(documentName).toUpperCase().replace(/-/g, '_'),
    documentName,
    requirement: 'MANDATORY',
    isMandatory: true,
    isOptional: false,
    appliesToAdult: true,
    appliesToMinor: true,
    appliesToStickerVisa: visaKind === 'STICKER_VISA',
    appliesToEVisa: visaKind === 'E_VISA' || visaKind === 'ETA',
    uploadRequired: true,
    physicalOriginalRequired: visaKind === 'STICKER_VISA' && documentName.toLowerCase().includes('passport'),
    courierRequired: visaKind === 'STICKER_VISA',
    sampleAvailable: false,
    requirementStatus: 'CONFIRMED',
    appliesTo: 'TRAVELER',
  }));

  return {
    mandatory,
    optional: [] as VisaDocumentRequirement[],
  };
};

const buildPricingLineItems = (visa: Pick<VisaType, 'id' | 'price' | 'currency'>): VisaPricingLineItem[] => {
  const breakdown = buildVisaPriceBreakdown(rupeesToMinor(visa.price), visa.currency);
  return breakdown.lines.map((line, index) => ({
    id: `${visa.id}-price-${index}`,
    label: line.label,
    type: line.type,
    amount: line.amountMinor / 100,
    amountMinor: line.amountMinor,
    currency: visa.currency,
    taxable: line.taxable,
    quantity: 1,
    includedInBasePrice: true,
  }));
};

const enrichVisaTypeCatalogue = (visa: VisaType): VisaType => {
  const visaKind = visa.visaKind ?? inferVisaKind(visa);
  const isStickerVisa = visaKind === 'STICKER_VISA';
  const pricingBreakdown = buildVisaPriceBreakdown(rupeesToMinor(visa.price), visa.currency);
  const pricingLineItems = visa.pricingLineItems ?? buildPricingLineItems(visa);
  const stickerRoutes = isStickerVisa ? [
    {
      id: `${visa.id}-bengaluru`,
      type: 'ROUND_TRIP' as const,
      origin: 'BENGALURU',
      destination: 'Processing centre',
      visaProductId: visa.id,
      originCityCode: 'BENGALURU',
      originCityLabel: 'Bengaluru',
      processingCentreCity: 'Bengaluru',
      courierFeeMinor: 150000,
      serviceFeeAdjustmentMinor: 0,
      estimatedOutboundDays: 1,
      estimatedReturnDays: 1,
      isActive: true,
    },
    {
      id: `${visa.id}-other-india`,
      type: 'ROUND_TRIP' as const,
      origin: 'OTHER_INDIA',
      destination: 'Processing centre',
      visaProductId: visa.id,
      originCityCode: 'OTHER_INDIA',
      originCityLabel: 'Other India',
      processingCentreCity: 'Bengaluru',
      courierFeeMinor: 250000,
      serviceFeeAdjustmentMinor: 0,
      estimatedOutboundDays: 2,
      estimatedReturnDays: 2,
      isActive: true,
    },
  ] : undefined;

  return {
    ...visa,
    destinationCode: visa.destination.toUpperCase().replace(/[^A-Z0-9]+/g, '_'),
    visaKind,
    entryType: visa.entryType ?? inferEntryType(visa.entry),
    purpose: visa.purpose ?? (visa.name.toLowerCase().includes('business') ? 'Business' : 'Tourism'),
    nationalityEligibility: visa.nationalityEligibility ?? ['IN'],
    processingTimeLabel: visa.processingTimeLabel ?? `Estimated processing time: ${visa.processingTime}`,
    documentRequirements: visa.documentRequirements ?? buildDocumentRequirements(visa, visaKind),
    pricingLineItems,
    pricing: visa.pricing ?? {
      visaFeeMinor: pricingBreakdown.visaFeeMinor,
      vvisaServiceFeeMinor: pricingBreakdown.serviceFeeMinor,
      courierFeeMinor: pricingBreakdown.courierFeeMinor,
      insuranceFeeMinor: pricingBreakdown.insuranceFeeMinor,
      convenienceFeeMinor: pricingBreakdown.convenienceFeeMinor,
      otherFeeMinor: pricingBreakdown.otherFeeMinor,
      discountMinor: pricingBreakdown.discountMinor,
      gstMinor: pricingBreakdown.gstMinor,
      totalAmountMinor: pricingBreakdown.totalMinor,
      currency: visa.currency,
      lines: pricingLineItems,
    },
    passportValidityRule: visa.passportValidityRule ?? {
      minimumMonthsFrom: 'ARRIVAL_DATE',
      minimumMonths: 6,
      rule: 'SIX_MONTHS_FROM_TRAVEL',
      blankPagesRequired: isStickerVisa ? 2 : 1,
    },
    minimumPassportValidityMonths: visa.minimumPassportValidityMonths ?? 6,
    courierRules: visa.courierRules ?? {
      required: isStickerVisa,
      available: isStickerVisa,
      physicalSubmissionRequired: isStickerVisa,
      courierRequired: isStickerVisa,
      courierDirection: isStickerVisa ? 'BOTH' : 'NOT_REQUIRED',
      submissionCentreName: isStickerVisa ? 'V-Visa Processing Desk' : undefined,
      submissionCity: isStickerVisa ? 'Bengaluru' : undefined,
      returnCourierAvailable: isStickerVisa,
      outboundCourierFeeMinor: isStickerVisa ? 150000 : undefined,
      returnCourierFeeMinor: isStickerVisa ? 150000 : undefined,
      passportCollectionAvailable: isStickerVisa,
      passportCollectionCities: isStickerVisa ? ['BENGALURU', 'OTHER_INDIA'] : undefined,
      routes: stickerRoutes,
      allowSelfDropOff: isStickerVisa,
      allowSelfCollection: isStickerVisa,
      notes: isStickerVisa ? 'Courier or self handover may be required for passport submission and collection.' : undefined,
    },
    stickerRoutes: visa.stickerRoutes ?? stickerRoutes,
  };
};

const mockVisaTypesRaw: VisaType[] = [
  // ==================== VIETNAM (8 entries) ====================
  {
    id: 'visa-001',
    destination: 'Vietnam',
    name: 'Lightning Fast Visa (6 Business Hours)',
    category: 'LIGHTNING_FAST',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '6 Business Hours',
    price: 8999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary'],
    cutoffTime: '11:30 AM',
  },
  {
    id: 'visa-002',
    destination: 'Vietnam',
    name: 'Evisa Vietnam 30 Days',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 2700,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-003',
    destination: 'Vietnam',
    name: 'Vietnam 90 Days Multiple Entry E-Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 12404,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },
  {
    id: 'visa-009',
    destination: 'Vietnam',
    name: 'Vietnam 90 Days E-Visa (Single Entry)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 4200,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary'],
  },
  {
    id: 'visa-010',
    destination: 'Vietnam',
    name: 'Vietnam 30 Days E-Visa on Arrival (Multiple Entry)',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 7500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Hotel Booking'],
  },

  // ==================== UAE (8 entries) ====================
  {
    id: 'visa-004',
    destination: 'UAE',
    name: 'UAE 30 Days Single Entry Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 6499,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-005',
    destination: 'UAE',
    name: 'UAE 60 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '60 days',
    duration: '60 days',
    processingTime: '5-7 Business Days',
    price: 14599,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement'],
  },
  {
    id: 'visa-014',
    destination: 'UAE',
    name: 'UAE 14 Days Single Entry Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '14 days',
    duration: '14 days',
    processingTime: '2-3 Business Days',
    price: 3999,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-015',
    destination: 'UAE',
    name: 'UAE 30 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement'],
  },
  {
    id: 'visa-016',
    destination: 'UAE',
    name: 'UAE 60 Days Single Entry Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '60 days',
    duration: '60 days',
    processingTime: '4-6 Business Days',
    price: 8999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement'],
  },
  {
    id: 'visa-017',
    destination: 'UAE',
    name: 'UAE 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 18499,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Travel Itinerary'],
  },

  // ==================== SINGAPORE (3 entries) ====================
  {
    id: 'visa-006',
    destination: 'Singapore',
    name: 'Singapore Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter'],
  },
  {
    id: 'visa-020',
    destination: 'Singapore',
    name: 'Singapore Business Visa (30 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement'],
  },
  {
    id: 'visa-021',
    destination: 'Singapore',
    name: 'Singapore 96 Hours Transit Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '4 days',
    duration: '4 days',
    processingTime: '2-3 Business Days',
    price: 2500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Onward Flight Ticket'],
  },

  // ==================== THAILAND (5 entries) ====================
  {
    id: 'visa-008',
    destination: 'Thailand',
    name: 'Thailand Tourist Visa (60 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '60 days',
    duration: '60 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },
  {
    id: 'visa-023',
    destination: 'Thailand',
    name: 'Thailand Visa on Arrival (15 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '15 days',
    duration: '15 days',
    processingTime: '1-2 Business Days',
    price: 1500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Return Flight Ticket', 'Hotel Booking'],
  },
  {
    id: 'visa-024',
    destination: 'Thailand',
    name: 'Thailand Tourist Visa (30 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },
  {
    id: 'visa-025',
    destination: 'Thailand',
    name: 'Thailand Multiple Entry Tourist Visa (60 Days)',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '6 months',
    duration: '60 days per entry',
    processingTime: '5-7 Business Days',
    price: 8500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter'],
  },
  {
    id: 'visa-026',
    destination: 'Thailand',
    name: 'Thailand Business Visa (90 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 12000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement'],
  },

  // ==================== AUSTRALIA (5 entries) ====================
  {
    id: 'visa-007',
    destination: 'Australia',
    name: 'Australia Visitors Visa (Subclass 600)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '12 months',
    duration: '3 months per entry',
    processingTime: '15-20 Business Days',
    price: 13499,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'National ID', 'ITR', 'Bank Statement', 'Salary Slips', 'Covering Letter', 'Form 54'],
  },
  {
    id: 'visa-027',
    destination: 'Australia',
    name: 'Australia Visitor Visa Subclass 600 (6 Months)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '12 months',
    duration: '6 months per entry',
    processingTime: '15-20 Business Days',
    price: 15999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'National ID', 'ITR', 'Bank Statement', 'Salary Slips', 'Covering Letter', 'Form 54'],
  },
  {
    id: 'visa-028',
    destination: 'Australia',
    name: 'Australia Visitor Visa Subclass 600 (12 Months)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '12 months',
    duration: '12 months per entry',
    processingTime: '20-25 Business Days',
    price: 18999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'National ID', 'ITR', 'Bank Statement', 'Salary Slips', 'Covering Letter', 'Form 54', 'Travel Insurance'],
  },
  {
    id: 'visa-029',
    destination: 'Australia',
    name: 'Australia Student Visa Subclass 500',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '5 years',
    duration: 'Duration of course',
    processingTime: '25-30 Business Days',
    price: 35999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Offer Letter', 'GTE Statement', 'Financial Documents', 'Health Insurance', 'English Test Scores'],
  },

  // ==================== MALAYSIA (3 entries) ====================
  {
    id: 'visa-031',
    destination: 'Malaysia',
    name: 'Malaysia 30 Days eNTRI',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '15 days',
    processingTime: '1-2 Business Days',
    price: 1800,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Return Flight Ticket', 'Hotel Booking'],
  },
  {
    id: 'visa-032',
    destination: 'Malaysia',
    name: 'Malaysia 30 Days eVisa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 3200,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },
  {
    id: 'visa-033',
    destination: 'Malaysia',
    name: 'Malaysia 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '90 days',
    duration: '30 days per entry',
    processingTime: '5-7 Business Days',
    price: 7500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'Travel Itinerary'],
  },

  // ==================== TURKEY (3 entries) ====================
  {
    id: 'visa-034',
    destination: 'Turkey',
    name: 'Turkey 30 Days e-Visa (Single Entry)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '1-2 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-035',
    destination: 'Turkey',
    name: 'Turkey 30 Days e-Visa (Multiple Entry)',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '30 days',
    duration: '30 days',
    processingTime: '1-2 Business Days',
    price: 6000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement'],
  },
  {
    id: 'visa-036',
    destination: 'Turkey',
    name: 'Turkey 90 Days e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '180 days',
    duration: '90 days',
    processingTime: '3-5 Business Days',
    price: 9500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement'],
  },

  // ==================== SRI LANKA (3 entries) ====================
  {
    id: 'visa-037',
    destination: 'Sri Lanka',
    name: 'Sri Lanka 30 Days ETA',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '1-2 Business Days',
    price: 1200,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Return Flight Ticket'],
  },
  {
    id: 'visa-038',
    destination: 'Sri Lanka',
    name: 'Sri Lanka 30 Days Business Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 3000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration'],
  },
  {
    id: 'visa-039',
    destination: 'Sri Lanka',
    name: 'Sri Lanka 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '90 days',
    duration: '30 days per entry',
    processingTime: '5-7 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Travel Itinerary'],
  },

  // ==================== MALDIVES (2 entries) ====================
  {
    id: 'visa-040',
    destination: 'Maldives',
    name: 'Maldives 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '1-2 Business Days',
    price: 2500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Hotel Booking Confirmation', 'Return Flight Ticket'],
  },
  {
    id: 'visa-041',
    destination: 'Maldives',
    name: 'Maldives 90 Days Business Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 6000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement'],
  },

  // ==================== USA (2 entries) ====================
  {
    id: 'visa-042',
    destination: 'USA',
    name: 'USA B1/B2 Visa (Interview Assisted)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '10 years',
    duration: '6 months per entry',
    processingTime: '15-20 Business Days',
    price: 8999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'DS-160 Confirmation', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Property Documents'],
  },
  {
    id: 'visa-043',
    destination: 'USA',
    name: 'USA B1/B2 Visa (Premium Processing)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '10 years',
    duration: '6 months per entry',
    processingTime: '7-10 Business Days',
    price: 14999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'DS-160 Confirmation', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Property Documents', 'Covering Letter'],
  },

  // ==================== UK (4 entries) ====================
  {
    id: 'visa-044',
    destination: 'UK',
    name: 'UK Standard Visitor Visa (6 Months)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '6 months',
    duration: '6 months',
    processingTime: '15-20 Business Days',
    price: 11999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Itinerary', 'Accommodation Proof'],
  },
  {
    id: 'visa-045',
    destination: 'UK',
    name: 'UK Long-term Visitor Visa (2 Years)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '2 years',
    duration: '6 months per entry',
    processingTime: '20-25 Business Days',
    price: 35999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Itinerary', 'Accommodation Proof', 'Covering Letter'],
  },
  {
    id: 'visa-046',
    destination: 'UK',
    name: 'UK Long-term Visitor Visa (5 Years)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '5 years',
    duration: '6 months per entry',
    processingTime: '25-30 Business Days',
    price: 55999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Itinerary', 'Accommodation Proof', 'Covering Letter', 'Property Documents'],
  },
  {
    id: 'visa-047',
    destination: 'UK',
    name: 'UK Long-term Visitor Visa (10 Years)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '10 years',
    duration: '6 months per entry',
    processingTime: '30-40 Business Days',
    price: 75999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Itinerary', 'Accommodation Proof', 'Covering Letter', 'Property Documents'],
  },

  // ==================== CANADA (3 entries) ====================
  {
    id: 'visa-048',
    destination: 'Canada',
    name: 'Canada Visitor Visa (Single Entry)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '6 months',
    duration: '6 months',
    processingTime: '15-25 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Itinerary', 'Purpose of Visit Letter'],
  },
  {
    id: 'visa-049',
    destination: 'Canada',
    name: 'Canada Visitor Visa (Multiple Entry)',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '10 years',
    duration: '6 months per entry',
    processingTime: '15-25 Business Days',
    price: 14999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Itinerary', 'Purpose of Visit Letter'],
  },
  {
    id: 'visa-050',
    destination: 'Canada',
    name: 'Canada Super Visa',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '10 years',
    duration: '5 years per entry',
    processingTime: '25-35 Business Days',
    price: 16999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Invitation from Child/Grandchild', 'Medical Insurance', 'Medical Exam Report'],
  },

  // ==================== JAPAN (3 entries) ====================
  {
    id: 'visa-051',
    destination: 'Japan',
    name: 'Japan 15 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '15 days',
    duration: '15 days',
    processingTime: '5-7 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter'],
  },
  {
    id: 'visa-052',
    destination: 'Japan',
    name: 'Japan 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'Hotel Booking'],
  },
  {
    id: 'visa-053',
    destination: 'Japan',
    name: 'Japan 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '1 year',
    duration: '30 days per entry',
    processingTime: '7-10 Business Days',
    price: 8000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Previous Japan Visas'],
  },

  // ==================== SOUTH KOREA (2 entries) ====================
  {
    id: 'visa-054',
    destination: 'South Korea',
    name: 'South Korea 30 Days Single Entry Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 4000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter'],
  },
  {
    id: 'visa-055',
    destination: 'South Korea',
    name: 'South Korea 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '1 year',
    duration: '30 days per entry',
    processingTime: '7-10 Business Days',
    price: 7500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR'],
  },

  // ==================== FRANCE / SCHENGEN (3 entries) ====================
  {
    id: 'visa-056',
    destination: 'France',
    name: 'Schengen Tourist Visa via France (30 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },
  {
    id: 'visa-057',
    destination: 'France',
    name: 'Schengen Business Visa via France (30 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance', 'Covering Letter'],
  },
  {
    id: 'visa-058',
    destination: 'France',
    name: 'Schengen Long-stay Visa via France (90 Days)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '6 months',
    duration: '90 days',
    processingTime: '25-30 Business Days',
    price: 18999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter', 'Accommodation Proof'],
  },

  // ==================== GERMANY (3 entries) ====================
  {
    id: 'visa-059',
    destination: 'Germany',
    name: 'Schengen Tourist Visa via Germany',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },
  {
    id: 'visa-060',
    destination: 'Germany',
    name: 'Schengen Business Visa via Germany',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance', 'Covering Letter'],
  },
  {
    id: 'visa-061',
    destination: 'Germany',
    name: 'Germany National Visa (Long Stay)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '1 year',
    duration: '1 year',
    processingTime: '30-45 Business Days',
    price: 25999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Covering Letter', 'Employment Contract', 'Qualification Certificates', 'Bank Statement', 'Health Insurance', 'Accommodation Proof'],
  },

  // ==================== ITALY (2 entries) ====================
  {
    id: 'visa-062',
    destination: 'Italy',
    name: 'Schengen Tourist Visa via Italy',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },
  {
    id: 'visa-063',
    destination: 'Italy',
    name: 'Schengen Business Visa via Italy',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance', 'Covering Letter'],
  },

  // ==================== SPAIN (2 entries) ====================
  {
    id: 'visa-064',
    destination: 'Spain',
    name: 'Schengen Tourist Visa via Spain',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },
  {
    id: 'visa-065',
    destination: 'Spain',
    name: 'Schengen Business Visa via Spain',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance', 'Covering Letter'],
  },

  // ==================== NEW ZEALAND (2 entries) ====================
  {
    id: 'visa-066',
    destination: 'New Zealand',
    name: 'New Zealand Visitor Visa',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '9 months',
    duration: '9 months',
    processingTime: '20-25 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Return Flight Ticket'],
  },
  {
    id: 'visa-067',
    destination: 'New Zealand',
    name: 'New Zealand Working Holiday Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '12 months',
    duration: '12 months',
    processingTime: '25-30 Business Days',
    price: 15999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement (min ₹3L)', 'Employment Letter', 'Medical Certificate', 'Police Clearance', 'Return Flight Ticket'],
  },

  // ==================== RUSSIA (3 entries) ====================
  {
    id: 'visa-068',
    destination: 'Russia',
    name: 'Russia 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '7-10 Business Days',
    price: 6500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Voucher', 'Travel Insurance'],
  },
  {
    id: 'visa-069',
    destination: 'Russia',
    name: 'Russia 30 Days Business Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '10-15 Business Days',
    price: 9500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Travel Insurance'],
  },
  {
    id: 'visa-070',
    destination: 'Russia',
    name: 'Russia 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '6 months',
    duration: '90 days',
    processingTime: '10-15 Business Days',
    price: 15000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance'],
  },

  // ==================== CHINA (3 entries) ====================
  {
    id: 'visa-071',
    destination: 'China',
    name: 'China 30 Days Tourist Visa (L Visa)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 7500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking', 'Bank Statement', 'Return Flight Ticket'],
  },
  {
    id: 'visa-072',
    destination: 'China',
    name: 'China 60 Days Business Visa (M Visa)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '60 days',
    duration: '60 days',
    processingTime: '7-10 Business Days',
    price: 12000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement'],
  },
  {
    id: 'visa-073',
    destination: 'China',
    name: 'China 10 Years Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '10 years',
    duration: '60 days per entry',
    processingTime: '7-10 Business Days',
    price: 25000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Employment Letter', 'ITR', 'Previous China Visas'],
  },

  // ==================== EGYPT (2 entries) ====================
  {
    id: 'visa-074',
    destination: 'Egypt',
    name: 'Egypt 30 Days e-Visa (Single Entry)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking'],
  },
  {
    id: 'visa-075',
    destination: 'Egypt',
    name: 'Egypt 30 Days e-Visa (Multiple Entry)',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Hotel Booking'],
  },

  // ==================== SAUDI ARABIA (2 entries) ====================
  {
    id: 'visa-076',
    destination: 'Saudi Arabia',
    name: 'Saudi Arabia 30 Days Tourist e-Visa',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '1 year',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 7999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Hotel Booking'],
  },
  {
    id: 'visa-077',
    destination: 'Saudi Arabia',
    name: 'Saudi Arabia 90 Days Multiple Entry e-Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '1 year',
    duration: '90 days',
    processingTime: '7-10 Business Days',
    price: 14999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'Hotel Booking'],
  },

  // ==================== OMAN (2 entries) ====================
  {
    id: 'visa-078',
    destination: 'Oman',
    name: 'Oman 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking'],
  },
  {
    id: 'visa-079',
    destination: 'Oman',
    name: 'Oman 30 Days Business Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 8500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement'],
  },

  // ==================== QATAR (2 entries) ====================
  {
    id: 'visa-080',
    destination: 'Qatar',
    name: 'Qatar 30 Days e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking'],
  },
  {
    id: 'visa-081',
    destination: 'Qatar',
    name: 'Qatar 90 Days Multiple Entry Visa',
    category: 'MULTI_ENTRY',
    entry: 'Multiple',
    validity: '90 days',
    duration: '30 days per entry',
    processingTime: '5-7 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Hotel Booking'],
  },

  // ==================== INDONESIA (3 entries) ====================
  {
    id: 'visa-082',
    destination: 'Indonesia',
    name: 'Indonesia 30 Days Visa on Arrival',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '1-2 Business Days',
    price: 2000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Return Flight Ticket'],
  },
  {
    id: 'visa-083',
    destination: 'Indonesia',
    name: 'Indonesia 60 Days B211A Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '60 days',
    duration: '60 days',
    processingTime: '5-7 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Travel Itinerary', 'Hotel Booking', 'Sponsor Letter'],
  },
  {
    id: 'visa-084',
    destination: 'Indonesia',
    name: 'Indonesia 180 Days B211A Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '180 days',
    duration: '180 days',
    processingTime: '7-10 Business Days',
    price: 9000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Bank Statement', 'Travel Itinerary', 'Hotel Booking', 'Sponsor Letter', 'Employment Letter'],
  },

  // ==================== MYANMAR (2 entries) ====================
  {
    id: 'visa-085',
    destination: 'Myanmar',
    name: 'Myanmar 28 Days e-Visa (Tourist)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '28 days',
    duration: '28 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking'],
  },
  {
    id: 'visa-086',
    destination: 'Myanmar',
    name: 'Myanmar 28 Days e-Visa (Business)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '28 days',
    duration: '28 days',
    processingTime: '5-7 Business Days',
    price: 6000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Hotel Booking'],
  },

  // ==================== CAMBODIA (2 entries) ====================
  {
    id: 'visa-087',
    destination: 'Cambodia',
    name: 'Cambodia 30 Days e-Visa (Tourist)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '2-3 Business Days',
    price: 2500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Return Flight Ticket'],
  },
  {
    id: 'visa-088',
    destination: 'Cambodia',
    name: 'Cambodia 30 Days e-Visa (Business)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Hotel Booking'],
  },

  // ==================== NEPAL (3 entries) ====================
  {
    id: 'visa-089',
    destination: 'Nepal',
    name: 'Nepal 15 Days Visa on Arrival',
    category: 'STANDARD',
    entry: 'Single',
    validity: '15 days',
    duration: '15 days',
    processingTime: 'Same Day',
    price: 800,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-090',
    destination: 'Nepal',
    name: 'Nepal 30 Days Visa on Arrival',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: 'Same Day',
    price: 1500,
    currency: 'INR',
    documents: ['Passport', 'Photo'],
  },
  {
    id: 'visa-091',
    destination: 'Nepal',
    name: 'Nepal 90 Days Visa on Arrival',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: 'Same Day',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary'],
  },

  // ==================== BHUTAN (2 entries) ====================
  {
    id: 'visa-092',
    destination: 'Bhutan',
    name: 'Bhutan 7 Days Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '7 days',
    duration: '7 days',
    processingTime: '5-7 Business Days',
    price: 4000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking Confirmation', 'Daily Package Payment Proof'],
  },
  {
    id: 'visa-093',
    destination: 'Bhutan',
    name: 'Bhutan 14 Days Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '14 days',
    duration: '14 days',
    processingTime: '5-7 Business Days',
    price: 6000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking Confirmation', 'Daily Package Payment Proof'],
  },

  // ==================== MAURITIUS (2 entries) ====================
  {
    id: 'visa-094',
    destination: 'Mauritius',
    name: 'Mauritius 60 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '60 days',
    duration: '60 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Return Flight Ticket', 'Hotel Booking'],
  },
  {
    id: 'visa-095',
    destination: 'Mauritius',
    name: 'Mauritius 90 Days Business Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: '5-7 Business Days',
    price: 8000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Hotel Booking'],
  },

  // ==================== SEYCHELLES (1 entry) ====================
  {
    id: 'visa-096',
    destination: 'Seychelles',
    name: 'Seychelles 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '2-3 Business Days',
    price: 2500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Return Flight Ticket', 'Hotel Booking', 'Bank Statement'],
  },

  // ==================== PHILIPPINES (2 entries) ====================
  {
    id: 'visa-097',
    destination: 'Philippines',
    name: 'Philippines 30 Days Visa Free (Processing Fee)',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Return Flight Ticket', 'Hotel Booking'],
  },
  {
    id: 'visa-098',
    destination: 'Philippines',
    name: 'Philippines 59 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '59 days',
    duration: '59 days',
    processingTime: '3-5 Business Days',
    price: 3000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Hotel Booking'],
  },

  // ==================== SWITZERLAND (2 entries) ====================
  {
    id: 'visa-099',
    destination: 'Switzerland',
    name: 'Schengen Tourist Visa via Switzerland',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },
  {
    id: 'visa-100',
    destination: 'Switzerland',
    name: 'Schengen Business Visa via Switzerland',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance', 'Covering Letter'],
  },

  // ==================== NETHERLANDS (2 entries) ====================
  {
    id: 'visa-101',
    destination: 'Netherlands',
    name: 'Schengen Tourist Visa via Netherlands',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },
  {
    id: 'visa-102',
    destination: 'Netherlands',
    name: 'Schengen Business Visa via Netherlands',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 12999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Business Invitation Letter', 'Company Registration', 'Bank Statement', 'Travel Insurance', 'Covering Letter'],
  },

  // ==================== ICELAND (1 entry) ====================
  {
    id: 'visa-103',
    destination: 'Iceland',
    name: 'Schengen Tourist Visa via Iceland',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },

  // ==================== IRELAND (1 entry) ====================
  {
    id: 'visa-104',
    destination: 'Ireland',
    name: 'Ireland Short Stay Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: '15-20 Business Days',
    price: 11999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },

  // ==================== GREECE (1 entry) ====================
  {
    id: 'visa-105',
    destination: 'Greece',
    name: 'Schengen Tourist Visa via Greece',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },

  // ==================== TANZANIA (1 entry) ====================
  {
    id: 'visa-106',
    destination: 'Tanzania',
    name: 'Tanzania 30 Days Tourist e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking', 'Yellow Fever Certificate'],
  },

  // ==================== KENYA (1 entry) ====================
  {
    id: 'visa-107',
    destination: 'Kenya',
    name: 'Kenya 30 Days Tourist e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking', 'Return Flight Ticket'],
  },

  // ==================== MOROCCO (1 entry) ====================
  {
    id: 'visa-108',
    destination: 'Morocco',
    name: 'Morocco 30 Days Tourist e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 3000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking', 'Bank Statement'],
  },

  // ==================== SOUTH AFRICA (1 entry) ====================
  {
    id: 'visa-109',
    destination: 'South Africa',
    name: 'South Africa 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '7-10 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'Return Flight Ticket', 'Yellow Fever Certificate'],
  },

  // ==================== FIJI (1 entry) ====================
  {
    id: 'visa-110',
    destination: 'Fiji',
    name: 'Fiji 120 Days Visitor Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '120 days',
    duration: '120 days',
    processingTime: '5-7 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Return Flight Ticket', 'Hotel Booking'],
  },

  // ==================== BAHRAIN (1 entry) ====================
  {
    id: 'visa-111',
    destination: 'Bahrain',
    name: 'Bahrain 30 Days e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 4000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking'],
  },

  // ==================== KUWAIT (1 entry) ====================
  {
    id: 'visa-112',
    destination: 'Kuwait',
    name: 'Kuwait 30 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '5-7 Business Days',
    price: 5500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking', 'Bank Statement'],
  },

  // ==================== AZERBAIJAN (1 entry) ====================
  {
    id: 'visa-113',
    destination: 'Azerbaijan',
    name: 'Azerbaijan 30 Days e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 3500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Hotel Booking'],
  },

  // ==================== GEORGIA (1 entry) ====================
  {
    id: 'visa-114',
    destination: 'Georgia',
    name: 'Georgia 30 Days e-Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '30 days',
    duration: '30 days',
    processingTime: '3-5 Business Days',
    price: 2000,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary'],
  },

  // ==================== PORTUGAL (1 entry) ====================
  {
    id: 'visa-115',
    destination: 'Portugal',
    name: 'Schengen Tourist Visa via Portugal',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '30 days',
    processingTime: '15-20 Business Days',
    price: 9999,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'ITR', 'Travel Insurance', 'Hotel Booking', 'Covering Letter'],
  },

  // ==================== BRAZIL (1 entry) ====================
  {
    id: 'visa-116',
    destination: 'Brazil',
    name: 'Brazil 90 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Single',
    validity: '90 days',
    duration: '90 days',
    processingTime: '10-15 Business Days',
    price: 7500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'Return Flight Ticket'],
  },

  // ==================== MEXICO (1 entry) ====================
  {
    id: 'visa-117',
    destination: 'Mexico',
    name: 'Mexico 180 Days Tourist Visa',
    category: 'STANDARD',
    entry: 'Multiple',
    validity: '180 days',
    duration: '180 days',
    processingTime: '7-10 Business Days',
    price: 4500,
    currency: 'INR',
    documents: ['Passport', 'Photo', 'Travel Itinerary', 'Bank Statement', 'Employment Letter', 'Hotel Booking'],
  },
];

export const mockVisaTypes: VisaType[] = mockVisaTypesRaw.map(enrichVisaTypeCatalogue);

const createTraveler = (overrides: Partial<import('@/types').Traveler> & { id: string; firstName: string; lastName: string; passportNumber: string }): import('@/types').Traveler => ({
  nationality: 'Indian',
  sex: 'Male',
  dateOfBirth: '1990-05-15',
  placeOfBirth: 'Bangalore',
  placeOfIssue: 'Bangalore',
  maritalStatus: 'Single',
  dateOfIssue: '2023-01-10',
  dateOfExpiry: '2033-01-09',
  isChild: false,
  status: 'APPROVED',
  referenceNo: `E260308INDR${overrides.passportNumber.slice(-6)}`,
  estimatedArrival: '2026-03-13',
  deliveredAt: '2026-03-12',
  ...overrides,
});

export const mockApplications: VisaApplication[] = [
  {
    id: 'app-001',
    agencyId: 'agency-001',
    groupId: 'grp-001',
    internalId: 'C7612934',
    groupName: 'SAPNA CHHAJER',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-24',
    returnDate: '2026-04-07',
    status: 'APPROVED',
    totalPrice: 21600,
    createdAt: '2026-03-07T18:43:00',
    updatedAt: '2026-03-12T10:00:00',
    travelers: [
      createTraveler({ id: 't-001', firstName: 'Hiyansh Amit', lastName: 'Chhajer', passportNumber: 'C7819328', isChild: true, dateOfBirth: '2018-08-22' }),
      createTraveler({ id: 't-002', firstName: 'Pratiksha', lastName: 'Jain', passportNumber: 'J7820156', sex: 'Female' }),
      createTraveler({ id: 't-003', firstName: 'Mukesh', lastName: 'Kumar', passportNumber: 'K8234512' }),
      createTraveler({ id: 't-004', firstName: 'Sapna', lastName: 'Chhajer', passportNumber: 'C7612934', sex: 'Female' }),
      createTraveler({ id: 't-005', firstName: 'Hiyanshi Amit', lastName: 'Chhajer', passportNumber: 'C7612935', isChild: true, dateOfBirth: '2020-03-15' }),
      createTraveler({ id: 't-006', firstName: 'Manya', lastName: 'Bohra', passportNumber: 'B6123456', isChild: true, dateOfBirth: '2019-11-08' }),
      createTraveler({ id: 't-007', firstName: 'Purvansh', lastName: 'Bohra', passportNumber: 'B6123457', isChild: true, dateOfBirth: '2021-06-20' }),
      createTraveler({ id: 't-008', firstName: 'Livi', lastName: 'Chhajer', passportNumber: 'C7612936', isChild: true, dateOfBirth: '2022-01-12' }),
    ],
  },
  {
    id: 'app-002',
    agencyId: 'agency-001',
    groupId: 'grp-002',
    internalId: 'G4521987',
    groupName: 'VISHAL GIREEYA',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-20',
    returnDate: '2026-04-03',
    status: 'APPROVED',
    totalPrice: 10800,
    createdAt: '2026-03-05T14:20:00',
    updatedAt: '2026-03-10T09:30:00',
    travelers: [
      createTraveler({ id: 't-009', firstName: 'Vishal', lastName: 'Gireeya', passportNumber: 'G4521987' }),
      createTraveler({ id: 't-010', firstName: 'Priya', lastName: 'Gireeya', passportNumber: 'G4521988', sex: 'Female' }),
      createTraveler({ id: 't-011', firstName: 'Arjun', lastName: 'Gireeya', passportNumber: 'G4521989', isChild: true, dateOfBirth: '2017-09-14' }),
      createTraveler({ id: 't-012', firstName: 'Meera', lastName: 'Gireeya', passportNumber: 'G4521990', isChild: true, dateOfBirth: '2020-04-25' }),
    ],
  },
  {
    id: 'app-003',
    agencyId: 'agency-001',
    groupId: 'grp-003',
    internalId: 'J6789012',
    groupName: 'KAUSHIK JAIN',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-04-01',
    returnDate: '2026-04-15',
    status: 'PAYMENT_PENDING',
    totalPrice: 5400,
    createdAt: '2026-03-10T11:00:00',
    updatedAt: '2026-03-10T11:00:00',
    travelers: [
      createTraveler({ id: 't-013', firstName: 'Kaushik', lastName: 'Jain', passportNumber: 'J6789012', status: 'PAYMENT_PENDING' }),
      createTraveler({ id: 't-014', firstName: 'Ritu', lastName: 'Jain', passportNumber: 'J6789013', sex: 'Female', status: 'PAYMENT_PENDING' }),
    ],
  },
  {
    id: 'app-004',
    agencyId: 'agency-001',
    groupName: 'AKASH KOTHARI',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-02-26',
    returnDate: '2026-03-12',
    status: 'APPROVED',
    totalPrice: 2700,
    createdAt: '2026-03-06T13:46:00',
    updatedAt: '2026-03-12T10:00:00',
    travelers: [
      createTraveler({ id: 't-015', firstName: 'Akash', lastName: 'Kothari', passportNumber: 'R1213598', referenceNo: 'E260308INDR121359397', estimatedArrival: '2026-03-13', deliveredAt: '2026-03-12' }),
    ],
  },
  {
    id: 'app-005',
    agencyId: 'agency-001',
    destination: 'Vietnam',
    visaType: 'Evisa Vietnam 30 Days',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-01',
    returnDate: '2026-03-15',
    status: 'APPROVED',
    totalPrice: 2700,
    createdAt: '2026-02-25T09:15:00',
    updatedAt: '2026-03-08T14:00:00',
    travelers: [
      createTraveler({ id: 't-016', firstName: 'Nisarga', lastName: 'Shavahalli Prakash', passportNumber: 'N9876543', referenceNo: 'E260308INDN987654321', estimatedArrival: '2026-03-05', deliveredAt: '2026-03-04' }),
    ],
  },
  {
    id: 'app-006',
    agencyId: 'agency-001',
    groupId: 'grp-004',
    internalId: 'M1234567',
    groupName: 'RAHUL SHARMA',
    destination: 'UAE',
    visaType: 'UAE 30 Days Single Entry Visa',
    visaCategory: 'STANDARD',
    travelDate: '2026-04-10',
    returnDate: '2026-05-10',
    status: 'SUBMITTED',
    totalPrice: 19497,
    createdAt: '2026-03-15T16:30:00',
    updatedAt: '2026-03-16T08:00:00',
    travelers: [
      createTraveler({ id: 't-017', firstName: 'Rahul', lastName: 'Sharma', passportNumber: 'M1234567', status: 'SUBMITTED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-018', firstName: 'Anita', lastName: 'Sharma', passportNumber: 'M1234568', sex: 'Female', status: 'SUBMITTED' }),
      createTraveler({ id: 't-019', firstName: 'Vikram', lastName: 'Sharma', passportNumber: 'M1234569', status: 'SUBMITTED' }),
    ],
  },
  // ==================== NEW APPLICATIONS ====================
  // app-007: UAE Group - SUBMITTED (Deepak Patel)
  {
    id: 'app-007',
    agencyId: 'agency-001',
    groupId: 'grp-005',
    internalId: 'S5566778',
    groupName: 'DEEPAK PATEL',
    destination: 'UAE',
    visaType: 'UAE 30 Days Single Entry Visa',
    visaCategory: 'STANDARD',
    travelDate: '2026-04-15',
    returnDate: '2026-05-15',
    status: 'SUBMITTED',
    totalPrice: 19497,
    createdAt: '2026-03-18T09:00:00',
    updatedAt: '2026-03-19T10:00:00',
    travelers: [
      createTraveler({ id: 't-020', firstName: 'Deepak', lastName: 'Patel', passportNumber: 'P5566778', status: 'SUBMITTED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-021', firstName: 'Rekha', lastName: 'Patel', passportNumber: 'P5566779', sex: 'Female', status: 'SUBMITTED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-022', firstName: 'Aarav', lastName: 'Patel', passportNumber: 'P5566780', isChild: true, dateOfBirth: '2016-12-03', status: 'SUBMITTED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
    ],
  },
  // app-008: Singapore Individual - APPROVED (Meera Rao)
  {
    id: 'app-008',
    agencyId: 'agency-001',
    groupName: 'MEERA RAO',
    destination: 'Singapore',
    visaType: 'Singapore Tourist Visa',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-20',
    returnDate: '2026-04-20',
    status: 'APPROVED',
    totalPrice: 4500,
    createdAt: '2026-03-02T11:00:00',
    updatedAt: '2026-03-08T14:00:00',
    travelers: [
      createTraveler({ id: 't-023', firstName: 'Meera', lastName: 'Rao', passportNumber: 'R8899001', sex: 'Female', dateOfBirth: '1988-07-22', referenceNo: 'E260308INDR889900111', estimatedArrival: '2026-03-18', deliveredAt: '2026-03-17' }),
    ],
  },
  // app-009: Thailand Group - PAYMENT_PENDING
  {
    id: 'app-009',
    agencyId: 'agency-001',
    groupId: 'grp-006',
    internalId: 'T3344556',
    groupName: 'SUNIL VERMA',
    destination: 'Thailand',
    visaType: 'Thailand Tourist Visa (60 Days)',
    visaCategory: 'STANDARD',
    travelDate: '2026-04-20',
    returnDate: '2026-05-20',
    status: 'PAYMENT_PENDING',
    totalPrice: 14000,
    createdAt: '2026-03-17T15:30:00',
    updatedAt: '2026-03-17T15:30:00',
    travelers: [
      createTraveler({ id: 't-024', firstName: 'Sunil', lastName: 'Verma', passportNumber: 'T3344556', status: 'PAYMENT_PENDING', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-025', firstName: 'Kavita', lastName: 'Verma', passportNumber: 'T3344557', sex: 'Female', dateOfBirth: '1991-03-18', status: 'PAYMENT_PENDING', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-026', firstName: 'Rohan', lastName: 'Verma', passportNumber: 'T3344558', isChild: true, dateOfBirth: '2019-06-11', status: 'PAYMENT_PENDING', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-027', firstName: 'Sanjay', lastName: 'Verma', passportNumber: 'T3344559', dateOfBirth: '1955-11-30', status: 'PAYMENT_PENDING', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
    ],
  },
  // app-010: Malaysia Individual - APPROVED
  {
    id: 'app-010',
    agencyId: 'agency-001',
    groupName: 'ANJALI DESHMUKH',
    destination: 'Malaysia',
    visaType: 'Malaysia 30 Days eVisa',
    visaCategory: 'STANDARD',
    travelDate: '2026-03-25',
    returnDate: '2026-04-25',
    status: 'APPROVED',
    totalPrice: 3200,
    createdAt: '2026-03-05T10:00:00',
    updatedAt: '2026-03-10T16:00:00',
    travelers: [
      createTraveler({ id: 't-028', firstName: 'Anjali', lastName: 'Deshmukh', passportNumber: 'D1122334', sex: 'Female', dateOfBirth: '1993-01-15', referenceNo: 'E260308INDD112233440', estimatedArrival: '2026-03-22', deliveredAt: '2026-03-21' }),
    ],
  },
  // app-011: USA Individual - DRAFT
  {
    id: 'app-011',
    agencyId: 'agency-001',
    groupName: 'RAJESH MENON',
    destination: 'USA',
    visaType: 'USA B1/B2 Visa (Interview Assisted)',
    visaCategory: 'STANDARD',
    travelDate: '2026-06-10',
    returnDate: '2026-07-10',
    status: 'DRAFT',
    totalPrice: 8999,
    createdAt: '2026-03-19T08:45:00',
    updatedAt: '2026-03-19T08:45:00',
    travelers: [
      createTraveler({ id: 't-029', firstName: 'Rajesh', lastName: 'Menon', passportNumber: 'M9988776', dateOfBirth: '1985-09-28', placeOfBirth: 'Kochi', placeOfIssue: 'Kochi', status: 'DRAFT', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
    ],
  },
  // app-012: Australia Group - VALIDATED
  {
    id: 'app-012',
    agencyId: 'agency-001',
    groupId: 'grp-007',
    internalId: 'K7788990',
    groupName: 'PRIYA NAIR',
    destination: 'Australia',
    visaType: 'Australia Visitor Visa Subclass 600 (6 Months)',
    visaCategory: 'STANDARD',
    travelDate: '2026-05-01',
    returnDate: '2026-11-01',
    status: 'VALIDATED',
    totalPrice: 31998,
    createdAt: '2026-03-14T12:00:00',
    updatedAt: '2026-03-18T09:00:00',
    travelers: [
      createTraveler({ id: 't-030', firstName: 'Priya', lastName: 'Nair', passportNumber: 'K7788990', sex: 'Female', dateOfBirth: '1987-04-12', placeOfBirth: 'Thiruvananthapuram', placeOfIssue: 'Thiruvananthapuram', status: 'VALIDATED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
      createTraveler({ id: 't-031', firstName: 'Arun', lastName: 'Nair', passportNumber: 'K7788991', dateOfBirth: '1984-11-05', placeOfBirth: 'Thiruvananthapuram', placeOfIssue: 'Thiruvananthapuram', status: 'VALIDATED', referenceNo: '', estimatedArrival: '', deliveredAt: '' }),
    ],
  },
];

export const mockTransactions: WalletTransaction[] = [
  { id: 'enKOd-67a3f201-a1b2', type: 'DEPOSIT', amount: 50000, method: 'BANK_TRANSFER', status: 'COMPLETED', description: 'Bank Transfer - YES Bank', createdAt: '2026-03-01T10:00:00' },
  { id: 'enKOd-APP-67a3f202-c3d4', type: 'PAYMENT', amount: -21600, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Sapna Chhajer Group (8 travelers)', createdAt: '2026-03-07T18:45:00' },
  { id: 'enKOd-APP-67a3f203-e5f6', type: 'PAYMENT', amount: -10800, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Vishal Gireeya Group (4 travelers)', createdAt: '2026-03-05T14:25:00' },
  { id: 'enKOd-APP-67a3f204-g7h8', type: 'PAYMENT', amount: -2700, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Akash Kothari', createdAt: '2026-03-06T13:50:00' },
  { id: 'enKOd-APP-67a3f205-i9j0', type: 'PAYMENT', amount: -2700, method: 'WALLET', status: 'COMPLETED', description: 'Vietnam Visa - Nisarga Shavahalli Prakash', createdAt: '2026-02-25T09:20:00' },
  { id: 'enKOd-67a3f206-k1l2', type: 'REFUND', amount: 500, method: 'WALLET', status: 'COMPLETED', description: 'Refund - Duplicate payment correction', createdAt: '2026-03-08T11:00:00' },
  { id: 'enKOd-67a3f207-m3n4', type: 'DEPOSIT', amount: 25000, method: 'UPI', status: 'COMPLETED', description: 'UPI Deposit', createdAt: '2026-03-10T09:00:00' },
  { id: 'enKOd-APP-67a3f208-o5p6', type: 'PAYMENT', amount: -19497, method: 'WALLET', status: 'COMPLETED', description: 'UAE Visa - Rahul Sharma Group (3 travelers)', createdAt: '2026-03-15T16:35:00' },
  { id: 'enKOd-67a3f209-q7r8', type: 'WITHDRAWAL', amount: -5403, method: 'BANK_TRANSFER', status: 'PENDING', description: 'Withdrawal to registered bank', createdAt: '2026-03-16T10:00:00' },
  { id: 'enKOd-67a3f20a-s9t0', type: 'DEPOSIT', amount: 10000, method: 'CREDIT_CARD', status: 'COMPLETED', description: 'Credit Card Deposit (2% fee: ₹200)', createdAt: '2026-03-12T14:30:00' },
];

export const mockAllianceLinks: AllianceLink[] = [];

export const mockOverstayCases: OverstayCase[] = [];

export const mockTestimonials = [
  { id: 1, company: 'Burnmiles', quote: 'VVisa has transformed how we handle visa applications. The bulk upload feature alone saves us 20+ hours every week. Our approval rate went from 85% to 99%.', author: 'Rajesh Mehta', role: 'Founder' },
  { id: 2, company: 'RV Holiday', quote: 'The wallet system and real-time tracking are game-changers. We can process 500+ applications in a single click. No other platform comes close.', author: 'Priya Iyer', role: 'Operations Head' },
  { id: 3, company: 'Jetways', quote: 'Switching to VVisa was the best decision we made. The 24/7 support and dedicated account manager make us feel like a priority client.', author: 'Amit Desai', role: 'Managing Director' },
  { id: 4, company: 'Family Holidays', quote: 'Our clients love the transparency. They can track their visa status in real-time. Our customer satisfaction scores have never been higher.', author: 'Sneha Kapoor', role: 'CEO' },
  { id: 5, company: 'Travozone', quote: 'Best prices in the market, hands down. The group application feature makes handling corporate travel seamless. Highly recommended for any B2B agency.', author: 'Karan Patel', role: 'Travel Director' },
];

export const mockFAQs = [
  { id: 1, question: 'What is ETA and How is it Calculated?', answer: 'ETA (Estimated Time of Arrival) is the projected date your visa will be approved and delivered. It is calculated based on the visa processing time for your selected category, the time of submission, and the destination country\'s embassy working hours. For example, our Lightning Fast visas submitted before 11:30 AM are typically processed within 6 business hours.' },
  { id: 2, question: 'Can I Track the Status of My Application?', answer: 'Yes! You can track every application in real-time from your dashboard. Each application goes through clear stages: Draft → Validated → Payment Pending → Paid → Submitted to Immigration → Approved. You\'ll also receive notifications for status changes via email and in-app alerts.' },
  { id: 3, question: 'Do You Provide Support After I Submit My Application?', answer: 'Absolutely. Our dedicated support team is available 24/7. Each agency is assigned a dedicated Account Manager who can be reached via phone, email, or in-app chat. We handle embassy follow-ups, document resubmissions, and any queries on your behalf.' },
  { id: 4, question: 'How Do I Make a Payment?', answer: 'We support three payment methods: Bank Transfer (0% fee), UPI (0% fee), and Credit Card (2% processing fee). Simply add funds to your VVisa Wallet, and all visa payments are automatically deducted when you submit applications. Deposits reflect within 30 minutes to 2 hours.' },
  { id: 5, question: 'Do I Get GST Invoices?', answer: 'Yes, you get GST-compliant invoices for every transaction. You can download invoices from the Applications page for each group or individual application. Ensure your GST certificate is uploaded in the Profile section to enable GST input credit.' },
  { id: 6, question: 'Do You Offer Support for Group Applications?', answer: 'Yes! Group applications are one of our core strengths. You can add up to 500 travelers in a single group application. Each traveler gets their own passport upload, document section, and status tracking. Group discounts are automatically applied for bulk applications.' },
];

export const popularDestinations = [
  'Vietnam', 'UAE', 'Singapore', 'Thailand', 'Australia', 'Malaysia', 'Turkey', 'Sri Lanka', 'Maldives', 'Indonesia',
  'USA', 'UK', 'Canada', 'Japan', 'South Korea', 'France', 'Germany', 'Italy', 'Spain', 'Switzerland',
  'Netherlands', 'New Zealand', 'Russia', 'China', 'Egypt', 'South Africa', 'Mauritius', 'Seychelles', 'Oman', 'Qatar',
  'Bahrain', 'Kuwait', 'Saudi Arabia', 'Myanmar', 'Cambodia', 'Nepal', 'Bhutan', 'Azerbaijan', 'Georgia', 'Armenia',
  'Kazakhstan', 'Philippines', 'Brazil', 'Mexico', 'Fiji', 'Tanzania', 'Kenya', 'Morocco', 'Iceland', 'Ireland',
  'Portugal', 'Greece', 'Czech Republic', 'Poland', 'Hungary', 'Austria', 'Denmark', 'Sweden', 'Norway', 'Finland',
];

export const statusConfig: Record<string, { label: string; bg: string; text: string; dot: string }> = {
  APPROVED: { label: 'Approved', bg: 'bg-emerald-950/50', text: 'text-emerald-400', dot: 'bg-emerald-400' },
  REJECTED: { label: 'Rejected', bg: 'bg-red-950/50', text: 'text-red-400', dot: 'bg-red-400' },
  PAYMENT_PENDING: { label: 'Pending Payment', bg: 'bg-amber-950/50', text: 'text-amber-400', dot: 'bg-amber-400' },
  PENDING: { label: 'Pending', bg: 'bg-amber-950/50', text: 'text-amber-400', dot: 'bg-amber-400' },
  SUBMITTED: { label: 'Submitted', bg: 'bg-blue-950/50', text: 'text-blue-400', dot: 'bg-blue-400' },
  DRAFT: { label: 'Draft', bg: 'bg-gray-800/50', text: 'text-gray-400', dot: 'bg-gray-400' },
  RECEIVED: { label: 'Received', bg: 'bg-blue-950/50', text: 'text-blue-400', dot: 'bg-blue-400' },
  VALIDATED: { label: 'Validated', bg: 'bg-indigo-950/50', text: 'text-indigo-400', dot: 'bg-indigo-400' },
  QUEUED: { label: 'Queued', bg: 'bg-purple-950/50', text: 'text-purple-400', dot: 'bg-purple-400' },
  PAID: { label: 'Paid', bg: 'bg-emerald-950/50', text: 'text-emerald-400', dot: 'bg-emerald-400' },
  OTP_PENDING: { label: 'OTP Pending', bg: 'bg-amber-950/50', text: 'text-amber-400', dot: 'bg-amber-400' },
  FAILED: { label: 'Failed', bg: 'bg-red-950/50', text: 'text-red-400', dot: 'bg-red-400' },
  CANCELLED: { label: 'Cancelled', bg: 'bg-gray-800/50', text: 'text-gray-400', dot: 'bg-gray-400' },
};

export const mockStats: DashboardStats = {
  totalApplications: 12,
  approvedThisMonth: 6,
  walletBalance: 28040,
  pendingPayment: 2,
};
