import type { ApprovedVisaProduct, VisaDocumentRequirement } from '@/types';

const publishedAt = '2026-06-26T00:00:00.000Z';
const publicationVersion = 'catalogue-v1-proof';
const publicationHash = 'proof-uk-uae-pt-kr-tr-v1';

function doc(
  id: string,
  name: string,
  requirement: VisaDocumentRequirement['requirement'],
  description: string,
  options: Partial<VisaDocumentRequirement> = {}
): VisaDocumentRequirement {
  return {
    id,
    label: requirement === 'MANDATORY' ? `${name} *` : name,
    documentCode: id.toUpperCase().replace(/[^A-Z0-9]+/g, '_'),
    documentName: name,
    requirement,
    description,
    uploadRequired: requirement !== 'INFORMATIONAL' && requirement !== 'INSTRUCTIONS',
    isMandatory: requirement === 'MANDATORY',
    isOptional: requirement === 'OPTIONAL',
    ...options,
  };
}

const commonPassportDocs = [
  doc('passport-front', 'Passport front page', 'MANDATORY', 'Clear passport bio page scan.'),
  doc('photo', 'Recent photograph', 'MANDATORY', 'Recent colour photograph as per destination specification.'),
];

export const productionApprovedProducts: ApprovedVisaProduct[] = [
  {
    id: 'prod-uk-standard-visitor-180-multiple',
    status: 'APPROVED',
    destination: 'United Kingdom',
    destinationCode: 'GB',
    name: 'UK Standard Visitor Visa - 180 Days',
    category: 'STANDARD',
    entry: 'Multiple',
    entryType: 'MULTIPLE',
    visaKind: 'STICKER_VISA',
    purpose: 'Tourism',
    validity: '180 days',
    duration: '180 days',
    processingTime: 'Estimated processing time: 15-30 working days',
    price: 15400,
    priceMinor: 1540000,
    currency: 'INR',
    documents: ['Passport front page', 'Recent photograph', 'Bank statement', 'Employment proof', 'Travel itinerary', 'Accommodation proof'],
    documentRequirements: {
      mandatory: [
        ...commonPassportDocs,
        doc('uk-bank-statement', 'Bank statement', 'MANDATORY', 'Recent bank statement or financial evidence.'),
        doc('uk-travel-itinerary', 'Travel itinerary', 'MANDATORY', 'Planned travel dates and itinerary.'),
        doc('uk-accommodation', 'Accommodation proof', 'MANDATORY', 'Hotel booking or host accommodation details.'),
      ],
      conditional: [
        doc('uk-employment-proof', 'Employment proof', 'CONDITIONAL', 'Required for employed travellers.', { conditionLabel: 'Employed travellers' }),
        doc('uk-minor-consent', 'Minor consent letter', 'CONDITIONAL', 'Required for applicants under 18 travelling without both parents.', { appliesToMinor: true }),
      ],
      optional: [doc('uk-cover-letter', 'Cover letter', 'OPTIONAL', 'Optional explanation of travel purpose.')],
      informational: [
        doc('uk-biometrics-info', 'Biometric appointment required', 'INFORMATIONAL', 'Applicant must attend biometric appointment at the assigned VAC.', {
          biometricRelated: true,
          uploadRequired: false,
          carryToAppointment: true,
        }),
      ],
    },
    pricingLineItems: [
      { id: 'uk-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 10200, amountMinor: 1020000, currency: 'INR', taxable: false },
      { id: 'uk-service-fee', label: 'Service Fee', type: 'SERVICE_FEE', amount: 4406.78, amountMinor: 440678, currency: 'INR', taxable: true },
      { id: 'uk-gst', label: 'GST (18%)', type: 'GST', amount: 793.22, amountMinor: 79322, currency: 'INR', taxable: false },
    ],
    pricing: {
      visaFeeMinor: 1020000,
      vvisaServiceFeeMinor: 440678,
      courierFeeMinor: 0,
      insuranceFeeMinor: 0,
      convenienceFeeMinor: 0,
      otherFeeMinor: 0,
      discountMinor: 0,
      gstMinor: 79322,
      totalAmountMinor: 1540000,
      currency: 'INR',
      lines: [],
    },
    courierRules: {
      required: true,
      available: true,
      physicalSubmissionRequired: true,
      courierRequired: false,
      courierDirection: 'NOT_SPECIFIED',
      submissionCentreName: 'UK Visa Application Centre',
      passportCollectionAvailable: true,
      routes: [],
    },
    jurisdictions: [
      {
        id: 'uk-india-countrywide-vac',
        visaProductId: 'prod-uk-standard-visitor-180-multiple',
        jurisdictionCode: 'UK_INDIA_VAC',
        jurisdictionLabel: 'India VAC Jurisdiction',
        destinationCountry: 'United Kingdom',
        applicantResidenceCountries: ['India'],
        submissionCentreName: 'UK Visa Application Centre',
        submissionCentreType: 'VFS',
        submissionCentreCity: 'Applicant selected VAC',
        biometricCentreCity: 'Applicant selected VAC',
        courierAvailable: true,
        physicalAppearanceRequired: true,
        priority: 100,
        isFallback: true,
        isActive: true,
        sourceText: 'UK visitor applications from India require online form and biometric appointment through visa application centre.',
        verificationStatus: 'REVIEW_REQUIRED',
      },
    ],
    passportValidityRule: { minimumMonths: 6, minimumMonthsFrom: 'ARRIVAL_DATE', rule: 'SIX_MONTHS_FROM_ARRIVAL', blankPagesRequired: 1 },
    publicationVersion,
    publicationHash,
    publishedAt,
  },
  {
    id: 'prod-portugal-schengen-tourist-90',
    status: 'APPROVED',
    destination: 'Portugal',
    destinationCode: 'PT',
    name: 'Portugal Schengen Tourist Visa - 90 Days',
    category: 'STANDARD',
    entry: 'Multiple',
    entryType: 'MULTIPLE',
    visaKind: 'STICKER_VISA',
    purpose: 'Tourism',
    validity: '180 days',
    duration: '90 days',
    processingTime: 'Estimated processing time: 15-21 working days',
    price: 12800,
    priceMinor: 1280000,
    currency: 'INR',
    documents: ['Passport front page', 'Recent photograph', 'Travel insurance', 'Bank statement', 'Accommodation proof'],
    documentRequirements: {
      mandatory: [
        ...commonPassportDocs,
        doc('pt-travel-insurance', 'Travel insurance', 'MANDATORY', 'Schengen travel insurance for the full travel period.'),
        doc('pt-bank-statement', 'Bank statement', 'MANDATORY', 'Recent financial evidence.'),
        doc('pt-accommodation', 'Accommodation proof', 'MANDATORY', 'Hotel booking or invitation/accommodation details.'),
      ],
      conditional: [doc('pt-employment-proof', 'Employment proof', 'CONDITIONAL', 'Required based on occupation profile.')],
      optional: [doc('pt-cover-letter', 'Cover letter', 'OPTIONAL', 'Optional cover letter to explain travel purpose.')],
      informational: [doc('pt-biometrics', 'Biometrics may be required', 'INFORMATIONAL', 'Applicant may need to attend the assigned visa centre.', { biometricRelated: true, uploadRequired: false })],
    },
    pricingLineItems: [
      { id: 'pt-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 7800, amountMinor: 780000, currency: 'INR', taxable: false },
      { id: 'pt-service-fee', label: 'Service Fee', type: 'SERVICE_FEE', amount: 4237.29, amountMinor: 423729, currency: 'INR', taxable: true },
      { id: 'pt-gst', label: 'GST (18%)', type: 'GST', amount: 762.71, amountMinor: 76271, currency: 'INR', taxable: false },
    ],
    pricing: { visaFeeMinor: 780000, vvisaServiceFeeMinor: 423729, courierFeeMinor: 0, insuranceFeeMinor: 0, convenienceFeeMinor: 0, otherFeeMinor: 0, discountMinor: 0, gstMinor: 76271, totalAmountMinor: 1280000, currency: 'INR', lines: [] },
    jurisdictions: [
      {
        id: 'pt-west-india-mumbai',
        visaProductId: 'prod-portugal-schengen-tourist-90',
        jurisdictionCode: 'PT_MUMBAI',
        jurisdictionLabel: 'Mumbai Jurisdiction',
        destinationCountry: 'Portugal',
        applicantResidenceStates: ['Maharashtra', 'Goa', 'Gujarat', 'Madhya Pradesh', 'Chhattisgarh'],
        submissionCentreName: 'VFS Portugal Mumbai',
        submissionCentreType: 'VFS',
        submissionCentreCity: 'Mumbai',
        biometricCentreCity: 'Mumbai',
        processingCentreCity: 'Consulate General of Portugal',
        courierAvailable: true,
        physicalAppearanceRequired: true,
        priority: 10,
        isFallback: false,
        isActive: true,
        sourceText: 'Portugal Schengen jurisdiction should be verified against official VFS/mission rules before final filing.',
        verificationStatus: 'REVIEW_REQUIRED',
      },
      {
        id: 'pt-india-manual',
        visaProductId: 'prod-portugal-schengen-tourist-90',
        jurisdictionCode: 'PT_MANUAL',
        jurisdictionLabel: 'Manual Portugal Jurisdiction Review',
        destinationCountry: 'Portugal',
        applicantResidenceCountries: ['India'],
        submissionCentreName: 'Manual review required',
        submissionCentreType: 'VISA_APPLICATION_CENTRE',
        courierAvailable: false,
        physicalAppearanceRequired: true,
        priority: 999,
        isFallback: true,
        isActive: true,
        sourceText: 'Fallback when state/city does not match a verified Portugal jurisdiction rule.',
        verificationStatus: 'REVIEW_REQUIRED',
      },
    ],
    passportValidityRule: { minimumMonths: 3, minimumMonthsFrom: 'DEPARTURE_DATE', rule: 'THREE_MONTHS_FROM_DEPARTURE', blankPagesRequired: 2 },
    publicationVersion,
    publicationHash,
    publishedAt,
  },
  {
    id: 'prod-south-korea-tourist-90',
    status: 'APPROVED',
    destination: 'South Korea',
    destinationCode: 'KR',
    name: 'South Korea Tourist Visa - 90 Days',
    category: 'STANDARD',
    entry: 'Single',
    entryType: 'SINGLE',
    visaKind: 'STICKER_VISA',
    purpose: 'Tourism',
    validity: '90 days',
    duration: '90 days',
    processingTime: 'Estimated processing time: 10-15 working days',
    price: 11200,
    priceMinor: 1120000,
    currency: 'INR',
    documents: ['Passport front page', 'Recent photograph', 'Bank statement', 'Employment proof'],
    documentRequirements: {
      mandatory: [...commonPassportDocs, doc('kr-bank-statement', 'Bank statement', 'MANDATORY', 'Financial evidence for the trip.')],
      conditional: [doc('kr-employment-proof', 'Employment proof', 'CONDITIONAL', 'Required for employed applicants.')],
      optional: [doc('kr-itinerary', 'Travel itinerary', 'OPTIONAL', 'Optional travel plan.')],
      informational: [doc('kr-centre-info', 'Submission centre varies by residence', 'INFORMATIONAL', 'Residence city/state may affect submission centre.', { uploadRequired: false })],
    },
    pricingLineItems: [
      { id: 'kr-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 6200, amountMinor: 620000, currency: 'INR', taxable: false },
      { id: 'kr-service-fee', label: 'Service Fee', type: 'SERVICE_FEE', amount: 4237.29, amountMinor: 423729, currency: 'INR', taxable: true },
      { id: 'kr-gst', label: 'GST (18%)', type: 'GST', amount: 762.71, amountMinor: 76271, currency: 'INR', taxable: false },
    ],
    pricing: { visaFeeMinor: 620000, vvisaServiceFeeMinor: 423729, courierFeeMinor: 0, insuranceFeeMinor: 0, convenienceFeeMinor: 0, otherFeeMinor: 0, discountMinor: 0, gstMinor: 76271, totalAmountMinor: 1120000, currency: 'INR', lines: [] },
    jurisdictions: [
      {
        id: 'kr-south-india-chennai',
        visaProductId: 'prod-south-korea-tourist-90',
        jurisdictionCode: 'KR_CHENNAI',
        jurisdictionLabel: 'Chennai Jurisdiction',
        destinationCountry: 'South Korea',
        applicantResidenceStates: ['Tamil Nadu', 'Karnataka', 'Kerala', 'Telangana', 'Andhra Pradesh'],
        submissionCentreName: 'Korea Visa Application Centre',
        submissionCentreType: 'VISA_APPLICATION_CENTRE',
        submissionCentreCity: 'Chennai',
        processingCentreCity: 'Consulate General',
        courierAvailable: true,
        physicalAppearanceRequired: false,
        priority: 10,
        isFallback: false,
        isActive: true,
        sourceText: 'South Korea city and jurisdiction variations require official confirmation before final filing.',
        verificationStatus: 'REVIEW_REQUIRED',
      },
    ],
    passportValidityRule: { minimumMonths: 6, minimumMonthsFrom: 'ARRIVAL_DATE', rule: 'SIX_MONTHS_FROM_ARRIVAL', blankPagesRequired: 2 },
    publicationVersion,
    publicationHash,
    publishedAt,
  },
  {
    id: 'prod-turkey-evisa-30',
    status: 'APPROVED',
    destination: 'Turkey',
    destinationCode: 'TR',
    name: 'Turkey E-Visa - 30 Days',
    category: 'STANDARD',
    entry: 'Single',
    entryType: 'SINGLE',
    visaKind: 'E_VISA',
    purpose: 'Tourism',
    validity: '180 days',
    duration: '30 days',
    processingTime: 'Estimated processing time: 1-3 working days',
    price: 7200,
    priceMinor: 720000,
    currency: 'INR',
    documents: ['Passport front page', 'Recent photograph'],
    documentRequirements: {
      mandatory: commonPassportDocs,
      conditional: [doc('tr-supporting-visa', 'Supporting valid visa/residence permit', 'CONDITIONAL', 'May be required depending on traveller eligibility.')],
      optional: [doc('tr-itinerary', 'Travel itinerary', 'OPTIONAL', 'Optional travel plan.')],
      informational: [doc('tr-electronic-delivery', 'Electronic visa delivery', 'INFORMATIONAL', 'No physical passport submission is expected for the eVisa variant.', { uploadRequired: false })],
    },
    pricingLineItems: [
      { id: 'tr-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 4300, amountMinor: 430000, currency: 'INR', taxable: false },
      { id: 'tr-service-fee', label: 'Service Fee', type: 'SERVICE_FEE', amount: 2457.63, amountMinor: 245763, currency: 'INR', taxable: true },
      { id: 'tr-gst', label: 'GST (18%)', type: 'GST', amount: 442.37, amountMinor: 44237, currency: 'INR', taxable: false },
    ],
    pricing: { visaFeeMinor: 430000, vvisaServiceFeeMinor: 245763, courierFeeMinor: 0, insuranceFeeMinor: 0, convenienceFeeMinor: 0, otherFeeMinor: 0, discountMinor: 0, gstMinor: 44237, totalAmountMinor: 720000, currency: 'INR', lines: [] },
    jurisdictions: [
      {
        id: 'tr-online',
        visaProductId: 'prod-turkey-evisa-30',
        jurisdictionCode: 'TR_ONLINE',
        jurisdictionLabel: 'Online eVisa',
        destinationCountry: 'Turkey',
        applicantResidenceCountries: ['India'],
        submissionCentreName: 'Online application',
        submissionCentreType: 'ONLINE',
        submissionCentreCity: 'Online',
        courierAvailable: false,
        physicalAppearanceRequired: false,
        priority: 1,
        isFallback: true,
        isActive: true,
        sourceText: 'Turkey eVisa handled online when eligibility criteria are met.',
        verificationStatus: 'REVIEW_REQUIRED',
      },
    ],
    passportValidityRule: { minimumMonths: 6, minimumMonthsFrom: 'ARRIVAL_DATE', rule: 'SIX_MONTHS_FROM_ARRIVAL', blankPagesRequired: 1 },
    publicationVersion,
    publicationHash,
    publishedAt,
  },
  {
    id: 'prod-turkey-sticker-90',
    status: 'APPROVED',
    destination: 'Turkey',
    destinationCode: 'TR',
    name: 'Turkey Sticker Visa - 90 Days',
    category: 'STANDARD',
    entry: 'Single',
    entryType: 'SINGLE',
    visaKind: 'STICKER_VISA',
    purpose: 'Tourism',
    validity: '180 days',
    duration: '90 days',
    processingTime: 'Estimated processing time: 7-15 working days',
    price: 9800,
    priceMinor: 980000,
    currency: 'INR',
    documents: ['Passport front page', 'Recent photograph', 'Bank statement'],
    documentRequirements: {
      mandatory: [...commonPassportDocs, doc('tr-sticker-bank-statement', 'Bank statement', 'MANDATORY', 'Financial evidence for the trip.')],
      conditional: [],
      optional: [doc('tr-sticker-itinerary', 'Travel itinerary', 'OPTIONAL', 'Optional travel plan.')],
      informational: [doc('tr-sticker-submission', 'Visa centre submission instruction', 'INFORMATIONAL', 'Physical passport submission may be required for the sticker variant.', { uploadRequired: false, physicalOriginalRequired: true, carryToAppointment: true })],
    },
    pricingLineItems: [
      { id: 'tr-sticker-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 6100, amountMinor: 610000, currency: 'INR', taxable: false },
      { id: 'tr-sticker-service-fee', label: 'Service Fee', type: 'SERVICE_FEE', amount: 3135.59, amountMinor: 313559, currency: 'INR', taxable: true },
      { id: 'tr-sticker-gst', label: 'GST (18%)', type: 'GST', amount: 564.41, amountMinor: 56441, currency: 'INR', taxable: false },
    ],
    pricing: { visaFeeMinor: 610000, vvisaServiceFeeMinor: 313559, courierFeeMinor: 0, insuranceFeeMinor: 0, convenienceFeeMinor: 0, otherFeeMinor: 0, discountMinor: 0, gstMinor: 56441, totalAmountMinor: 980000, currency: 'INR', lines: [] },
    courierRules: {
      required: false,
      available: false,
      physicalSubmissionRequired: true,
      courierRequired: false,
      courierDirection: 'NOT_SPECIFIED',
      submissionCentreName: 'Turkey visa application centre',
      submissionCity: 'Jurisdiction based',
      courierInstructions: 'Submission centre and passport handling must be confirmed during jurisdiction review.',
      passportCollectionAvailable: true,
      routes: [],
    },
    jurisdictions: [
      {
        id: 'tr-sticker-india-manual',
        visaProductId: 'prod-turkey-sticker-90',
        jurisdictionCode: 'TR_STICKER_MANUAL',
        jurisdictionLabel: 'Turkey Sticker Jurisdiction Review',
        destinationCountry: 'Turkey',
        applicantResidenceCountries: ['India'],
        submissionCentreName: 'Manual jurisdiction review required',
        submissionCentreType: 'VISA_APPLICATION_CENTRE',
        courierAvailable: false,
        physicalAppearanceRequired: true,
        priority: 100,
        isFallback: true,
        isActive: true,
        sourceText: 'Turkey sticker visa jurisdiction and centre rules require official confirmation before final filing.',
        verificationStatus: 'REVIEW_REQUIRED',
      },
    ],
    passportValidityRule: { minimumMonths: 6, minimumMonthsFrom: 'ARRIVAL_DATE', rule: 'SIX_MONTHS_FROM_ARRIVAL', blankPagesRequired: 1 },
    publicationVersion,
    publicationHash,
    publishedAt,
  },
];
