import type { ApprovedVisaProduct } from '@/types';

export const stampMyVisaApprovedProducts: ApprovedVisaProduct[] = [
  {
    id: 'stampmyvisa-ae-evisa-30',
    status: 'APPROVED',
    destination: 'United Arab Emirates',
    destinationCode: 'AE',
    name: 'Dubai Tourist Visa - 30 Days',
    category: 'STANDARD',
    entry: 'Single',
    entryType: 'SINGLE',
    visaKind: 'E_VISA',
    purpose: 'Tourism',
    validity: '60 days',
    duration: '30 days',
    processingTime: 'Estimated processing time: 3-5 working days',
    price: 6400,
    priceMinor: 640000,
    currency: 'INR',
    documents: ['Passport front page', 'Recent photograph', 'Bank statement', 'Employment proof'],
    documentRequirements: {
      mandatory: [
        {
          id: 'ae-evisa-passport-front',
          label: 'Passport front page *',
          documentCode: 'PASSPORT_FRONT',
          documentName: 'Passport front page',
          description: 'Upload passport front page.',
          requirement: 'MANDATORY',
          uploadRequired: true,
          isMandatory: true,
          appliesToEVisa: true,
        },
        {
          id: 'ae-evisa-photo',
          label: 'Recent photograph *',
          documentCode: 'PHOTO',
          documentName: 'Recent photograph',
          description: 'Upload a recent photograph.',
          requirement: 'MANDATORY',
          uploadRequired: true,
          isMandatory: true,
          appliesToEVisa: true,
        },
      ],
      conditional: [
        {
          id: 'ae-evisa-bank-statement',
          label: 'Bank statement',
          documentCode: 'BANK_STATEMENT',
          documentName: 'Bank statement',
          description: 'Required when immigration asks for financial evidence.',
          requirement: 'CONDITIONAL',
          conditionLabel: 'When financial proof is requested',
          uploadRequired: true,
        },
      ],
      optional: [
        {
          id: 'ae-evisa-employment-proof',
          label: 'Employment proof',
          documentCode: 'EMPLOYMENT_PROOF',
          documentName: 'Employment proof',
          description: 'Optional supporting document.',
          requirement: 'OPTIONAL',
          uploadRequired: true,
          isOptional: true,
        },
      ],
      informational: [
        {
          id: 'ae-evisa-processing-estimate',
          label: 'Estimated processing time is not guaranteed',
          requirement: 'INFORMATIONAL',
          description: 'Supplier timelines are estimates only.',
          uploadRequired: false,
        },
      ],
    },
    pricingLineItems: [
      { id: 'ae-evisa-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 2900, amountMinor: 290000, currency: 'INR', taxable: false },
      { id: 'ae-evisa-service-fee', label: 'Service Fee', type: 'SERVICE_FEE', amount: 2966.1, amountMinor: 296610, currency: 'INR', taxable: true },
      { id: 'ae-evisa-gst', label: 'GST (18%)', type: 'GST', amount: 533.9, amountMinor: 53390, currency: 'INR', taxable: false },
    ],
    pricing: {
      visaFeeMinor: 290000,
      vvisaServiceFeeMinor: 296610,
      courierFeeMinor: 0,
      insuranceFeeMinor: 0,
      convenienceFeeMinor: 0,
      otherFeeMinor: 0,
      discountMinor: 0,
      gstMinor: 53390,
      totalAmountMinor: 640000,
      currency: 'INR',
      lines: [],
    },
  },
  {
    id: 'stampmyvisa-ae-sticker-90',
    status: 'APPROVED',
    destination: 'United Arab Emirates',
    destinationCode: 'AE',
    name: 'UAE E-Visa - 90 Days',
    category: 'STANDARD',
    entry: 'Single',
    entryType: 'SINGLE',
    visaKind: 'E_VISA',
    purpose: 'Tourism',
    validity: '90 days',
    duration: '90 days',
    processingTime: 'Estimated processing time: 7-10 working days',
    price: 9828,
    priceMinor: 982800,
    currency: 'INR',
    documents: ['Passport front page scan', 'Recent photograph', 'Invitation letter', 'Travel itinerary'],
    documentRequirements: {
      mandatory: [
        {
          id: 'ae-online-passport-front',
          label: 'Passport front page scan *',
          documentCode: 'PASSPORT_FRONT',
          documentName: 'Passport front page scan',
          description: 'Upload passport scan for the application record.',
          requirement: 'MANDATORY',
          uploadRequired: true,
          physicalOriginalRequired: false,
          courierRequired: false,
          appliesToEVisa: true,
          isMandatory: true,
        },
        {
          id: 'ae-online-photo',
          label: 'Recent photograph *',
          documentCode: 'PHOTO',
          documentName: 'Recent photograph',
          description: 'Upload a recent photograph.',
          requirement: 'MANDATORY',
          uploadRequired: true,
          appliesToEVisa: true,
          isMandatory: true,
        },
      ],
      conditional: [
        {
          id: 'ae-sticker-invitation-letter',
          label: 'Invitation letter',
          documentCode: 'INVITATION_LETTER',
          documentName: 'Invitation letter',
          description: 'Required when invited by friend or family.',
          requirement: 'CONDITIONAL',
          conditionLabel: 'Invited by friend or family',
          uploadRequired: true,
        },
      ],
      optional: [
        {
          id: 'ae-sticker-itinerary',
          label: 'Travel itinerary',
          documentCode: 'TRAVEL_ITINERARY',
          documentName: 'Travel itinerary',
          description: 'Optional travel plan.',
          requirement: 'OPTIONAL',
          uploadRequired: true,
          isOptional: true,
        },
      ],
      informational: [
        {
          id: 'ae-online-processing-instruction',
          label: 'Estimated processing time is not guaranteed',
          requirement: 'INFORMATIONAL',
          description: 'Supplier timelines are estimates only.',
          uploadRequired: false,
          courierRequired: false,
        },
      ],
    },
    pricingLineItems: [
      { id: 'ae-online-visa-fee', label: 'Visa Fee', type: 'VISA_FEE', amount: 2900, amountMinor: 290000, currency: 'INR', taxable: false },
      { id: 'ae-online-vfs-fee', label: 'VFS Fee / pax', type: 'VFS_FEE', amount: 5158, amountMinor: 515800, currency: 'INR', taxable: false },
      { id: 'ae-online-service-fee', label: 'Service Fee / pax', type: 'SERVICE_FEE', amount: 1500, amountMinor: 150000, currency: 'INR', taxable: true },
      { id: 'ae-online-gst', label: 'GST (18%)', type: 'GST', amount: 270, amountMinor: 27000, currency: 'INR', taxable: false },
    ],
    pricing: {
      visaFeeMinor: 290000,
      vvisaServiceFeeMinor: 150000,
      courierFeeMinor: 0,
      insuranceFeeMinor: 0,
      convenienceFeeMinor: 0,
      otherFeeMinor: 515800,
      discountMinor: 0,
      gstMinor: 27000,
      totalAmountMinor: 982800,
      currency: 'INR',
      lines: [],
    },
    stickerRoutes: [],
    courierRules: {
      required: false,
      available: false,
      physicalSubmissionRequired: false,
      courierRequired: false,
      courierDirection: 'NOT_REQUIRED',
      passportCollectionAvailable: false,
      passportCollectionCities: [],
      routes: [],
    },
  },
];
