import assert from 'node:assert/strict'; import test from 'node:test';
import { adminApplicationDraftSchema, adminApplicationSubmitSchema, applicationStatusUpdateSchema, contentPublishSchema, contentRollbackSchema, dashboardDraftSchema, documentStatusSchema, partnerAdminNoteSchema, partnerProfileSchema, statusDraftSchema } from '../src/server/admin/workflow-schemas.ts';
import { supportModeAllows } from '../src/server/admin/support-session-policy.ts';

test('admin application draft requires partner-safe applicant and audit reason',()=>{const result=adminApplicationDraftSchema.safeParse({visaProductId:'visa-1',reason:'Customer requested assisted application',applicant:{firstName:'Asha',lastName:'Rao',passportNumber:'P1234567',nationality:'Indian'}});assert.equal(result.success,true);assert.equal(adminApplicationDraftSchema.safeParse({visaProductId:'visa-1',reason:'short',applicant:{}}).success,false)});
test('submission and content publishing require exact typed confirmations',()=>{assert.equal(adminApplicationSubmitSchema.safeParse({confirmation:'SUBMIT',reason:'Reviewed with partner',walletDeduction:false}).success,true);assert.equal(adminApplicationSubmitSchema.safeParse({confirmation:'submit',reason:'Reviewed with partner'}).success,false);assert.equal(contentPublishSchema.safeParse({versionId:'v1',confirmation:'PUBLISH',reason:'Approved production copy'}).success,true);assert.equal(contentRollbackSchema.safeParse({versionId:'v1',confirmation:'ROLLBACK',reason:'Restore prior approved copy'}).success,true)});
test('dashboard drafts keep publishable layout metadata',()=>{assert.equal(dashboardDraftSchema.safeParse({sectionKey:'recent-applications',reason:'Update partner dashboard title',snapshot:{title:'Latest applications',isVisible:true,displayOrder:50,targetAudience:{type:'all_partners'}}}).success,true)});
test('status drafts constrain progress and require complete labels',()=>{const base={code:'PROCESSING',reason:'Clarify partner-facing status',snapshot:{adminLabel:'Processing',partnerLabel:'Under Processing',partnerDescription:'Your application is being processed.',colorToken:'info',displayOrder:90,progressPercent:82,isPartnerVisible:true,isAdminVisible:true,isTerminal:false,isSuccess:false,isFailure:false,isActive:true}};assert.equal(statusDraftSchema.safeParse(base).success,true);assert.equal(statusDraftSchema.safeParse({...base,snapshot:{...base.snapshot,progressPercent:101}}).success,false)});
test('partner profile writes require typed confirmation and audit reason',()=>{const payload={name:'Acme Travel',ownerName:'Asha Rao',email:'owner@example.com',country:'India',status:'APPROVED',kycStatus:'APPROVED',confirmation:'UPDATE',reason:'Partner confirmed corrected company details'};assert.equal(partnerProfileSchema.safeParse(payload).success,true);assert.equal(partnerProfileSchema.safeParse({...payload,confirmation:'update'}).success,false)});
test('document and application status controls require typed confirmation',()=>{assert.equal(documentStatusSchema.safeParse({status:'VERIFIED',confirmation:'UPDATE',reason:'Reviewed the uploaded passport'}).success,true);assert.equal(applicationStatusUpdateSchema.safeParse({status:'PROCESSING',confirmation:'UPDATE',reason:'Submission accepted by operations'}).success,true)});
test('admin notes require content and an audit reason',()=>{assert.equal(partnerAdminNoteSchema.safeParse({note:'Partner asked for a callback tomorrow.',reason:'Record partner support request'}).success,true);assert.equal(partnerAdminNoteSchema.safeParse({note:'',reason:'short'}).success,false)});
test('support mode capabilities are monotonic and view-only blocks writes',()=>{assert.equal(supportModeAllows('view_only','support'),false);assert.equal(supportModeAllows('support','support'),true);assert.equal(supportModeAllows('support','operations'),false);assert.equal(supportModeAllows('operations','support'),true)});
