export type CareersFeatureFlag =
  | 'CAREERS_SAAS_ENABLED'
  | 'CAREERS_PACKAGES_ENABLED'
  | 'CAREERS_PAYMENTS_ENABLED'
  | 'CAREERS_CHECKOUT_ENABLED'
  | 'CAREERS_LIVE_PAYMENTS_ENABLED'
  | 'CAREERS_ONBOARDING_ENABLED'
  | 'CAREERS_RESUME_UPLOAD_ENABLED'
  | 'CAREERS_INTERNAL_CONSOLE_ENABLED'
  | 'CAREERS_LIVE_DISCOVERY_ENABLED'
  | 'CAREERS_APPLICATION_KIT_ENABLED'
  | 'CAREERS_BROWSER_EXECUTION_ENABLED'
  | 'CAREERS_AUTO_SUBMIT_ENABLED'
  | 'CAREERS_EMAIL_DRAFTS_ENABLED'
  | 'CAREERS_EMAIL_SEND_ENABLED'
  | 'CAREERS_REPLY_SYNC_ENABLED'
  | 'CAREERS_CRM_SYNC_ENABLED'
  | 'CAREERS_WORKDRIVE_UPLOAD_ENABLED'
  | 'CAREERS_GOOGLE_CALENDAR_ENABLED'
  | 'CAREERS_OUTLOOK_CALENDAR_ENABLED'
  | 'CAREERS_ZOHO_CALENDAR_ENABLED'
  | 'CAREERS_GOOGLE_MEET_ENABLED'
  | 'CAREERS_ZOOM_ENABLED'
  | 'CAREERS_TEAMS_ENABLED'
  | 'CAREERS_CALENDAR_EVENT_CREATION_ENABLED'
  | 'CAREERS_CALENDAR_REMINDERS_ENABLED'
  | 'CAREERS_EMPLOYER_RESPONSE_SYNC_ENABLED'
  | 'CAREERS_INTERVIEW_DETECTION_ENABLED';

export const CAREERS_FEATURE_FLAGS: CareersFeatureFlag[] = [
  'CAREERS_SAAS_ENABLED',
  'CAREERS_PACKAGES_ENABLED',
  'CAREERS_PAYMENTS_ENABLED',
  'CAREERS_CHECKOUT_ENABLED',
  'CAREERS_LIVE_PAYMENTS_ENABLED',
  'CAREERS_ONBOARDING_ENABLED',
  'CAREERS_RESUME_UPLOAD_ENABLED',
  'CAREERS_INTERNAL_CONSOLE_ENABLED',
  'CAREERS_LIVE_DISCOVERY_ENABLED',
  'CAREERS_APPLICATION_KIT_ENABLED',
  'CAREERS_BROWSER_EXECUTION_ENABLED',
  'CAREERS_AUTO_SUBMIT_ENABLED',
  'CAREERS_EMAIL_DRAFTS_ENABLED',
  'CAREERS_EMAIL_SEND_ENABLED',
  'CAREERS_REPLY_SYNC_ENABLED',
  'CAREERS_CRM_SYNC_ENABLED',
  'CAREERS_WORKDRIVE_UPLOAD_ENABLED',
  'CAREERS_GOOGLE_CALENDAR_ENABLED',
  'CAREERS_OUTLOOK_CALENDAR_ENABLED',
  'CAREERS_ZOHO_CALENDAR_ENABLED',
  'CAREERS_GOOGLE_MEET_ENABLED',
  'CAREERS_ZOOM_ENABLED',
  'CAREERS_TEAMS_ENABLED',
  'CAREERS_CALENDAR_EVENT_CREATION_ENABLED',
  'CAREERS_CALENDAR_REMINDERS_ENABLED',
  'CAREERS_EMPLOYER_RESPONSE_SYNC_ENABLED',
  'CAREERS_INTERVIEW_DETECTION_ENABLED',
];

export function careersFeatureEnabled(flag: CareersFeatureFlag) {
  return process.env[flag]?.trim().toLowerCase() === 'true';
}

export function careersFeatureSnapshot(): Record<CareersFeatureFlag, boolean> {
  return Object.fromEntries(CAREERS_FEATURE_FLAGS.map((flag) => [flag, careersFeatureEnabled(flag)])) as Record<CareersFeatureFlag, boolean>;
}

export function careersSafeMutationEnabled() {
  return (
    careersFeatureEnabled('CAREERS_SAAS_ENABLED') &&
    careersFeatureEnabled('CAREERS_ONBOARDING_ENABLED')
  );
}
