'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';

export function DashboardSectionEditor({ section }: { section: { key: string; name: string; displayOrder: number; isVisible: boolean; config: unknown } }) {
  const config = (section.config ?? {}) as Record<string, unknown>;
  const [open, setOpen] = useState(false); const [versionId, setVersionId] = useState<string | null>(null); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false);
  const [title, setTitle] = useState(String(config.title ?? section.name)); const [description, setDescription] = useState(String(config.description ?? '')); const [ctaLabel, setCtaLabel] = useState(String(config.ctaLabel ?? '')); const [ctaRoute, setCtaRoute] = useState(String(config.ctaRoute ?? '')); const [visible, setVisible] = useState(section.isVisible); const [order, setOrder] = useState(section.displayOrder); const [reason, setReason] = useState('');
  async function saveDraft() { setPending(true); setMessage(''); const response = await fetch('/api/admin/dashboard-sections/draft', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sectionKey: section.key, reason, snapshot: { ...config, title, description, ctaLabel, ctaRoute, isVisible: visible, displayOrder: order, targetAudience: { type: 'all_partners' } } }) }); const body = await response.json(); if (response.ok) { setVersionId(body.version.id); setMessage(`Draft version ${body.version.version} saved.`); } else setMessage(body.error?.message ?? 'Unable to save draft.'); setPending(false); }
  async function publish() { if (!versionId) return; setPending(true); const response = await fetch('/api/admin/dashboard-sections/publish', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ versionId, confirmation: 'PUBLISH', reason }) }); const body = await response.json(); setMessage(response.ok ? 'Published. Refreshing dashboard configuration.' : body.error?.message ?? 'Unable to publish.'); setPending(false); if (response.ok) setTimeout(() => location.reload(), 500); }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline">Edit</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Edit {section.name}</DialogTitle></DialogHeader><div className="grid gap-3"><div><Label>Title</Label><Input value={title} onChange={e=>setTitle(e.target.value)} /></div><div><Label>Description</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><Label>CTA label</Label><Input value={ctaLabel} onChange={e=>setCtaLabel(e.target.value)} /></div><div><Label>CTA route</Label><Input value={ctaRoute} onChange={e=>setCtaRoute(e.target.value)} /></div></div><div className="flex items-center justify-between"><Label>Visible</Label><Switch checked={visible} onCheckedChange={setVisible} /></div><div><Label>Display order</Label><Input type="number" value={order} onChange={e=>setOrder(Number(e.target.value))} /></div><div><Label>Audit reason</Label><Textarea value={reason} onChange={e=>setReason(e.target.value)} /></div>{message && <p className="text-sm text-vvisa-text-secondary">{message}</p>}</div><DialogFooter><Button variant="outline" onClick={saveDraft} disabled={pending || reason.trim().length < 8}>Save Draft</Button><Button onClick={publish} disabled={pending || !versionId}>Publish</Button></DialogFooter></DialogContent></Dialog>;
}
