'use client';

import { useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

type Profile = { name:string; ownerName:string; email:string; phone:string; whatsapp:string; addressLine1:string; addressLine2:string; city:string; state:string; country:string; zipCode:string; gstNumber:string; panCard:string; status:string; kycStatus:string; partnerTier:string; pricingPlan:string; accountManager:string };
const profileFields: Array<[keyof Profile,string]> = [['name','Agency name'],['ownerName','Owner name'],['email','Business email'],['phone','Phone'],['whatsapp','WhatsApp'],['addressLine1','Address line 1'],['addressLine2','Address line 2'],['city','City'],['state','State'],['country','Country'],['zipCode','Pincode'],['gstNumber','GST'],['panCard','PAN'],['partnerTier','Partner tier'],['pricingPlan','Pricing plan'],['accountManager','Account manager']];

export function PartnerProfileForm({ partnerUid, profile, enabled, supportSessionId }: { partnerUid:string; profile:Profile; enabled:boolean; supportSessionId?:string }) {
  const [pending,setPending]=useState(false); const [message,setMessage]=useState('');
  async function submit(formData:FormData){ setPending(true); const payload=Object.fromEntries(profileFields.map(([key])=>[key,String(formData.get(key)??'')||null])); const response=await fetch(`/api/admin/partners/${partnerUid}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,status:formData.get('status'),kycStatus:formData.get('kycStatus'),supportSessionId,confirmation:formData.get('confirmation'),reason:formData.get('reason')})}); const body=await response.json(); setMessage(response.ok?'Partner profile updated and audited.':body.error?.message??'Update failed.');setPending(false);if(response.ok)setTimeout(()=>location.reload(),600); }
  return <form action={submit} className="grid gap-3 md:grid-cols-2">{profileFields.map(([key,label])=><div key={key}><Label>{label}</Label><Input name={key} defaultValue={profile[key]} readOnly={!enabled} required={key==='name'||key==='email'||key==='country'}/></div>)}<div><Label>Account status</Label><Select name="status" defaultValue={profile.status} disabled={!enabled}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['DRAFT','EMAIL_VERIFICATION_PENDING','DOCUMENTS_PENDING','UNDER_REVIEW','APPROVED','REJECTED','SUSPENDED'].map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select></div><div><Label>KYC status</Label><Select name="kycStatus" defaultValue={profile.kycStatus} disabled={!enabled}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['DRAFT','EMAIL_VERIFICATION_PENDING','DOCUMENTS_PENDING','UNDER_REVIEW','APPROVED','REJECTED','SUSPENDED'].map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select></div>{enabled&&<><div className="md:col-span-2"><Label>Reason</Label><Textarea name="reason" minLength={8} required/></div><div><Label>Type UPDATE</Label><Input name="confirmation" required/></div><div className="flex items-end"><Button className="w-full" disabled={pending}>{pending?'Updating...':'Update Partner Profile'}</Button></div></>}{message&&<p className="md:col-span-2 text-sm">{message}</p>}</form>;
}

export function PartnerAdminNoteForm({partnerUid,supportSessionId}:{partnerUid:string;supportSessionId?:string}){const[pending,setPending]=useState(false),[message,setMessage]=useState('');async function submit(formData:FormData){setPending(true);const response=await fetch(`/api/admin/partners/${partnerUid}/notes`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note:formData.get('note'),reason:formData.get('reason'),supportSessionId})});const body=await response.json();setMessage(response.ok?'Note added.':body.error?.message??'Unable to add note.');setPending(false);if(response.ok)setTimeout(()=>location.reload(),600)}return <form action={submit} className="space-y-3"><div><Label>Internal note</Label><Textarea name="note" minLength={3} required/></div><div><Label>Reason</Label><Input name="reason" minLength={8} required/></div><Button disabled={pending}>{pending?'Adding...':'Add Admin Note'}</Button>{message&&<p className="text-sm">{message}</p>}</form>}

export function DocumentActions({id}:{id:string}){const[message,setMessage]=useState('');async function update(status:string){const reason=window.prompt(status==='REQUESTED'?'Reason for requesting replacement':'Reason for marking document received');if(!reason||reason.trim().length<8)return;const response=await fetch(`/api/admin/documents/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,confirmation:'UPDATE',reason})});const body=await response.json();setMessage(response.ok?'Updated':body.error?.message??'Failed');if(response.ok)setTimeout(()=>location.reload(),500)}return <div className="flex flex-wrap items-center gap-2"><Button asChild size="sm" variant="outline"><a href={`/api/admin/documents/${id}/file`} target="_blank" rel="noreferrer"><ExternalLink className="mr-1 size-3"/>View</a></Button><Button size="sm" variant="outline" onClick={()=>update('VERIFIED')}>Received</Button><Button size="sm" variant="outline" onClick={()=>update('REQUESTED')}>Replace</Button>{message&&<span className="text-xs">{message}</span>}</div>}

export function ApplicationStatusAction({id,current}:{id:string;current:string}){const[status,setStatus]=useState(current),[message,setMessage]=useState('');async function update(){const reason=window.prompt('Reason for status update');if(!reason||reason.trim().length<8)return;const response=await fetch(`/api/admin/applications/${id}/status`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,confirmation:'UPDATE',reason})});const body=await response.json();setMessage(response.ok?'Updated':body.error?.message??'Failed');if(response.ok)setTimeout(()=>location.reload(),500)}return <div className="flex items-center gap-2"><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent>{['DOCUMENTS_PENDING','READY_FOR_REVIEW','UNDER_INTERNAL_REVIEW','PAYMENT_PENDING','PAID','SUBMISSION_PENDING','SUBMITTED','PROCESSING','ADDITIONAL_DOCUMENTS_REQUIRED','APPROVED','REJECTED','CANCELLED'].map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select><Button size="sm" variant="outline" onClick={update} disabled={status===current}>Update</Button>{message&&<span className="text-xs">{message}</span>}</div>}
