-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "aadhaarNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "aadhaarName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "aadhaarAddress" TEXT;
