import Link from 'next/link';
import { redirect } from 'next/navigation';
import { Activity, ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, FileText, Gauge, LogOut, Orbit, Radar, Settings2, ShieldCheck } from 'lucide-react';
import { db } from '@/lib/db';
import { requireSession } from '@/server/auth/session';
import { careersFeatureSnapshot } from '@/server/careers/feature-flags';
import { careerCandidateFacingStatus } from '@/server/careers/onboarding';
import { MittoDashboardActions } from '@/components/careers/MittoDashboardActions';

export const metadata = { title: { absolute: 'Command center | Mitto Career' }, description: 'Your private Mitto Career automation workspace.' };

export default async function MittoDashboardPage() {
  const session = await requireSession().catch(() => null);
  if (!session) redirect('/login');
  const candidate = await db.careerCandidate.findFirst({ where: { userId: session.user.id }, include: { preferences: true, resumes: { orderBy: { createdAt: 'desc' }, take: 5 }, serviceRequests: { orderBy: { createdAt: 'desc' }, take: 1 }, statusEvents: { orderBy: { createdAt: 'desc' }, take: 6 } }, orderBy: { createdAt: 'desc' } });
  const connections = await db.careerConnection.findMany({ where: { userId: session.user.id }, select: { provider: true, connected: true } }).catch(() => []);
  const flags = careersFeatureSnapshot();

  return <main className="mitto-career min-h-screen text-white"><div className="mitto-aurora" aria-hidden="true" /><header className="sticky top-0 z-50 border-b border-white/8 bg-[#070912]/85 backdrop-blur-2xl"><div className="mx-auto flex h-20 max-w-[1480px] items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-2xl border border-cyan-300/25 bg-cyan-300/10 text-cyan-200"><Orbit className="size-5" /></span><span><b className="block">Mitto Career</b><small className="text-[10px] uppercase tracking-[.22em] text-slate-500">Command center</small></span></Link><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-400 sm:block">{session.user.email}</span><a href="/api/auth/logout" className="rounded-full border border-white/10 p-2.5 text-slate-400 hover:text-white" aria-label="Log out"><LogOut className="size-4" /></a></div></div></header>
    <div className="relative z-10 mx-auto max-w-[1480px] px-5 py-10 lg:px-8"><section className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="mitto-eyebrow"><Activity className="size-4" /> Live workspace</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Good to see you, {candidate?.fullName?.split(' ')[0] ?? session.user.name?.split(' ')[0] ?? 'there'}.</h1><p className="mt-3 text-slate-400">Your profile, integrations, service state, and approval-controlled automation in one place.</p></div><Link href="/careers/onboarding" className="mitto-button">{candidate ? 'Edit career profile' : 'Complete career profile'} <ArrowRight className="size-4" /></Link></section>
    {!candidate ? <section className="mitto-glass mt-10 rounded-[1.6rem] p-8"><BriefcaseBusiness className="size-7 text-cyan-200" /><h2 className="mt-6 text-2xl font-semibold">Build your candidate profile first</h2><p className="mt-3 max-w-2xl text-slate-400">This unlocks private resume uploads, matching preferences, connection records, packages, and the CareerOps workspace.</p><Link href="/careers/onboarding" className="mitto-button mt-6">Start profile <ArrowRight className="size-4" /></Link></section> : <>
      <section className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={Gauge} label="Profile" value={`${candidate.profileCompletionPercent}%`} detail={careerCandidateFacingStatus(candidate.status)} /><Metric icon={FileText} label="Resumes" value={String(candidate.resumes.length)} detail={candidate.resumes[0]?.status.replaceAll('_',' ') ?? 'Upload required'} /><Metric icon={Radar} label="Discovery" value={flags.CAREERS_DISCOVERY_ENABLED ? 'Enabled' : 'Gated'} detail={flags.CAREERS_LIVE_DISCOVERY_ENABLED ? 'Live provider allowed' : 'Fixture or review mode'} /><Metric icon={ShieldCheck} label="Execution" value={flags.CAREERS_BROWSER_EXECUTION_ENABLED ? 'Controlled' : 'Disabled'} detail={flags.CAREERS_AUTO_SUBMIT_ENABLED ? 'Approval policy applies' : 'No automatic submission'} /></section>
      <section className="mt-8"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-200">Workspace setup</p><h2 className="mt-2 text-2xl font-semibold">Resume and connections</h2></div><Link href="/careers/dashboard/connections" className="text-sm text-slate-400 hover:text-white">Manage connections</Link></div><MittoDashboardActions candidateId={candidate.id} initialConnections={connections.map(item => ({ provider: item.provider, connected: item.connected }))} /></section>
      <section className="mt-8 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="mitto-glass rounded-[1.5rem] p-6"><div className="flex items-center gap-2"><Settings2 className="size-5 text-cyan-200" /><h2 className="font-semibold">Automation readiness</h2></div><div className="mt-6 grid gap-3">{[['Profile intelligence',candidate.resumes.length ? 'Ready for review' : 'Waiting for resume'],['Opportunity discovery',flags.CAREERS_DISCOVERY_ENABLED ? 'Enabled' : 'Behind feature flag'],['Application kit',flags.CAREERS_APPLICATION_KIT_ENABLED ? 'Enabled' : 'Behind feature flag'],['Browser execution',flags.CAREERS_BROWSER_EXECUTION_ENABLED ? 'Approval controlled' : 'Disabled'],['Employer response sync',flags.CAREERS_EMPLOYER_RESPONSE_SYNC_ENABLED ? 'Enabled' : 'Coming next']].map(([label,value]) => <div key={label} className="flex items-center justify-between gap-4 rounded-2xl border border-white/8 bg-black/20 p-4 text-sm"><span className="text-slate-300">{label}</span><span className="text-right text-slate-500">{value}</span></div>)}</div></div><div className="mitto-glass rounded-[1.5rem] p-6"><div className="flex items-center gap-2"><Clock3 className="size-5 text-violet-200" /><h2 className="font-semibold">Recent activity</h2></div><div className="mt-6 space-y-3">{candidate.statusEvents.length ? candidate.statusEvents.map(event => <div key={event.id} className="rounded-2xl border border-white/8 bg-black/20 p-4"><p className="flex items-center gap-2 text-sm font-medium"><CheckCircle2 className="size-4 text-emerald-300" />{event.label}</p><p className="mt-2 text-xs leading-5 text-slate-500">{event.detail ?? 'Status recorded'}</p></div>) : <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">Activity appears as your profile and automation move forward.</p>}</div></div></section>
    </>}</div></main>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Gauge; label: string; value: string; detail: string }) { return <div className="mitto-glass rounded-[1.4rem] p-5"><div className="flex items-center justify-between"><span className="rounded-xl bg-white/5 p-2.5 text-cyan-200"><Icon className="size-5" /></span><span className="text-[10px] uppercase tracking-[.18em] text-slate-600">{label}</span></div><p className="mt-7 text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
