export interface CountryConfig {
  id: string;
  name: string;
  isoCode: string;
  flag: string;
  lat: number;
  lng: number;
  available: boolean;
  featured: boolean;
  comingSoon?: boolean;
  visaTypes: string[];
  route: string;
}

export const countriesData: CountryConfig[] = [
  {
    id: 'vietnam',
    name: 'Vietnam',
    isoCode: 'VN',
    flag: '🇻🇳',
    lat: 14.0583,
    lng: 108.2772,
    available: true,
    featured: true,
    visaTypes: ['Lightning Fast Visa', 'E-Visa 30 Days', 'E-Visa 90 Days'],
    route: '/explore?destination=Vietnam',
  },
  {
    id: 'united-kingdom',
    name: 'United Kingdom',
    isoCode: 'GB',
    flag: '🇬🇧',
    lat: 55.3781,
    lng: -3.4360,
    available: true,
    featured: true,
    visaTypes: ['Tourist Visa', 'Business Visa', 'Student Visa'],
    route: '/explore?destination=United Kingdom',
  },
  {
    id: 'united-states',
    name: 'United States',
    isoCode: 'US',
    flag: '🇺🇸',
    lat: 37.0902,
    lng: -95.7129,
    available: true,
    featured: true,
    visaTypes: ['B1/B2 Visitor', 'F1 Student Visa', 'C1 Transit Visa'],
    route: '/explore?destination=United States',
  },
  {
    id: 'canada',
    name: 'Canada',
    isoCode: 'CA',
    flag: '🇨🇦',
    lat: 56.1304,
    lng: -106.3468,
    available: true,
    featured: true,
    visaTypes: ['Visitor Visa', 'Student Permit', 'Super Visa'],
    route: '/explore?destination=Canada',
  },
  {
    id: 'australia',
    name: 'Australia',
    isoCode: 'AU',
    flag: '🇦🇺',
    lat: -25.2744,
    lng: 133.7751,
    available: true,
    featured: true,
    visaTypes: ['Visitor Visa (Subclass 600)', 'Student Visa'],
    route: '/explore?destination=Australia',
  },
  {
    id: 'germany',
    name: 'Germany',
    isoCode: 'DE',
    flag: '🇩🇪',
    lat: 51.1657,
    lng: 10.4515,
    available: true,
    featured: true,
    visaTypes: ['Schengen Tourist', 'Schengen Business', 'National Student'],
    route: '/explore?destination=Germany',
  },
  {
    id: 'france',
    name: 'France',
    isoCode: 'FR',
    flag: '🇫🇷',
    lat: 46.2276,
    lng: 2.2137,
    available: true,
    featured: true,
    visaTypes: ['Schengen Tourist', 'Schengen Business', 'Long Stay Visa'],
    route: '/explore?destination=France',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    isoCode: 'SG',
    flag: '🇸🇬',
    lat: 1.3521,
    lng: 103.8198,
    available: true,
    featured: true,
    visaTypes: ['e-Tourist Visa', 'Entry Visa', 'Business Visa'],
    route: '/explore?destination=Singapore',
  },
  {
    id: 'thailand',
    name: 'Thailand',
    isoCode: 'TH',
    flag: '🇹🇭',
    lat: 15.8700,
    lng: 100.9925,
    available: true,
    featured: true,
    visaTypes: ['e-Visa Tourist', 'Visa on Arrival', 'Multiple Entry Tourist'],
    route: '/explore?destination=Thailand',
  },
  {
    id: 'united-arab-emirates',
    name: 'United Arab Emirates',
    isoCode: 'AE',
    flag: '🇦🇪',
    lat: 23.4241,
    lng: 53.8478,
    available: true,
    featured: true,
    visaTypes: ['30 Days Tourist', '60 Days Tourist', 'Multi-Entry Transit'],
    route: '/explore?destination=United Arab Emirates',
  },
  {
    id: 'japan',
    name: 'Japan',
    isoCode: 'JP',
    flag: '🇯🇵',
    lat: 36.2048,
    lng: 138.2529,
    available: true,
    featured: false,
    visaTypes: ['e-Tourist Visa', 'Short Term Stay', 'Multiple Entry Tourist'],
    route: '/explore?destination=Japan',
  },
  {
    id: 'malaysia',
    name: 'Malaysia',
    isoCode: 'MY',
    flag: '🇲🇾',
    lat: 4.2105,
    lng: 101.9758,
    available: true,
    featured: false,
    visaTypes: ['eNTRI Visa', 'e-Tourist Single Entry', 'e-Tourist Multiple Entry'],
    route: '/explore?destination=Malaysia',
  },
  {
    id: 'turkey',
    name: 'Turkey',
    isoCode: 'TR',
    flag: '🇹🇷',
    lat: 38.9637,
    lng: 35.2433,
    available: true,
    featured: false,
    visaTypes: ['e-Tourist Visa', 'Sticker Visa Support'],
    route: '/explore?destination=Turkey',
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    isoCode: 'LK',
    flag: '🇱🇰',
    lat: 7.8731,
    lng: 80.7718,
    available: true,
    featured: false,
    visaTypes: ['ETA Tourist', 'ETA Business', 'ETA Transit'],
    route: '/explore?destination=Sri Lanka',
  },
  {
    id: 'maldives',
    name: 'Maldives',
    isoCode: 'MV',
    flag: '🇲🇻',
    lat: 3.2028,
    lng: 73.2207,
    available: true,
    featured: false,
    visaTypes: ['Tourist Visa on Arrival'],
    route: '/explore?destination=Maldives',
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    isoCode: 'ID',
    flag: '🇮🇩',
    lat: -0.7893,
    lng: 113.9213,
    available: true,
    featured: false,
    visaTypes: ['e-VOA (B211A)', 'Tourist Visa 30 Days'],
    route: '/explore?destination=Indonesia',
  },
  {
    id: 'saudi-arabia',
    name: 'Saudi Arabia',
    isoCode: 'SA',
    flag: '🇸🇦',
    lat: 23.8859,
    lng: 45.0792,
    available: true,
    featured: false,
    visaTypes: ['e-Tourist Visa', 'Family Visit Visa', 'Umrah Visa'],
    route: '/explore?destination=Saudi Arabia',
  },
  {
    id: 'russia',
    name: 'Russia',
    isoCode: 'RU',
    flag: '🇷🇺',
    lat: 61.5240,
    lng: 105.3188,
    available: true,
    featured: false,
    visaTypes: ['Unified e-Visa', 'Tourist Sticker Visa'],
    route: '/explore?destination=Russia',
  },
  {
    id: 'china',
    name: 'China',
    isoCode: 'CN',
    flag: '🇨🇳',
    lat: 35.8617,
    lng: 104.1954,
    available: true,
    featured: false,
    visaTypes: ['L Tourist Visa', 'M Business Visa'],
    route: '/explore?destination=China',
  },
  {
    id: 'brazil',
    name: 'Brazil',
    isoCode: 'BR',
    flag: '🇧🇷',
    lat: -14.2350,
    lng: -51.9253,
    available: false,
    featured: false,
    comingSoon: true,
    visaTypes: ['Tourist Visa', 'Business Visa'],
    route: '/explore?destination=Brazil',
  },
  {
    id: 'mexico',
    name: 'Mexico',
    isoCode: 'MX',
    flag: '🇲🇽',
    lat: 23.6345,
    lng: -102.5528,
    available: false,
    featured: false,
    comingSoon: true,
    visaTypes: ['Tourist Visa', 'Transit Visa'],
    route: '/explore?destination=Mexico',
  },
];
