import type { z } from 'zod';
import type { Prisma } from '@prisma/client';
import { db } from '@/lib/db';
import { apiError } from '@/lib/api-response';

import { cataloguePublishSchema, checklistDraftSchema, priceDraftSchema, productDraftSchema } from './catalogue-schemas';
export { cataloguePublishSchema, checklistDraftSchema, priceDraftSchema, productDraftSchema } from './catalogue-schemas';

export async function saveProductDraft(input:z.infer<typeof productDraftSchema>&{adminUid:string}){const latest=await db.visaProductVersion.findFirst({where:{visaProductId:input.productId},orderBy:{version:'desc'}});return db.visaProductVersion.create({data:{visaProductId:input.productId,version:(latest?.version??0)+1,snapshot:input.snapshot as Prisma.InputJsonValue,reviewStatus:'REVIEW_REQUIRED',approvedBy:input.adminUid}})}
export async function publishProductDraft(id:string,adminUid:string){const draft=await db.visaProductVersion.findUnique({where:{id}});if(!draft)throw apiError('RESOURCE_NOT_FOUND','Product draft not found.',404);const parsed=productDraftSchema.shape.snapshot.safeParse(draft.snapshot);if(!parsed.success)throw apiError('INVALID_ADMIN_MUTATION','Stored product draft is invalid.',409);return db.$transaction(async tx=>{await tx.visaProductVersion.updateMany({where:{visaProductId:draft.visaProductId,reviewStatus:'PUBLISHED'},data:{reviewStatus:'APPROVED'}});await tx.visaProductVersion.update({where:{id},data:{reviewStatus:'PUBLISHED',approvedBy:adminUid,approvedAt:new Date()}});return tx.visaProduct.update({where:{id:draft.visaProductId},data:{...parsed.data,badges:parsed.data.badges as Prisma.InputJsonValue}})})}
export async function savePriceDraft(input:z.infer<typeof priceDraftSchema>){const total=Math.max(0,input.adultPriceMinor+input.governmentFeeMinor+input.serviceFeeMinor+input.taxMinor+input.markupMinor-input.discountMinor);return db.visaPrice.create({data:{visaProductId:input.productId,currency:input.currency,adultPriceMinor:input.adultPriceMinor,childPriceMinor:input.childPriceMinor,infantPriceMinor:input.infantPriceMinor,visaFeeMinor:input.governmentFeeMinor,vvisaServiceFeeMinor:input.serviceFeeMinor,supplierCostMinor:input.supplierCostMinor,gstMinor:input.taxMinor,discountMinor:input.discountMinor,markupMinor:input.markupMinor,suggestedB2cMinor:input.suggestedB2cMinor,entryType:input.entryType,processingType:input.processingType,travellerType:input.travellerType,totalAmountMinor:total,isActive:false,validFrom:new Date(input.validFrom),validUntil:input.validUntil?new Date(input.validUntil):null}})}
export async function publishPriceDraft(id:string){const draft=await db.visaPrice.findUnique({where:{id}});if(!draft)throw apiError('RESOURCE_NOT_FOUND','Price draft not found.',404);return db.$transaction(async tx=>{await tx.visaPrice.updateMany({where:{visaProductId:draft.visaProductId,isActive:true},data:{isActive:false}});const price=await tx.visaPrice.update({where:{id},data:{isActive:true}});await tx.visaProduct.update({where:{id:draft.visaProductId},data:{amountMinor:price.totalAmountMinor,currency:price.currency,pricingVersion:`admin-${Date.now()}`}});return price})}
export async function saveChecklistDraft(input:z.infer<typeof checklistDraftSchema>){const data={visaProductId:input.productId,documentCode:input.documentCode,documentName:input.documentName,description:input.description,isMandatory:input.requirementType==='required',isOptional:input.requirementType==='optional',requirementType:input.requirementType,acceptedFormats:input.acceptedFormats as Prisma.InputJsonValue,maximumFileSizeBytes:input.maximumFileSizeBytes,sampleDocumentUrl:input.sampleDocumentUrl,templateDocumentUrl:input.templateDocumentUrl,translationRequired:input.translationRequired,notarisationRequired:input.notarisationRequired,apostilleRequired:input.apostilleRequired,attestationRequired:input.attestationRequired,displayOrder:input.displayOrder,internalVerificationNote:input.internalVerificationNote,requirementStatus:'REVIEW_REQUIRED' as const};return input.requirementId?db.visaDocumentRequirement.update({where:{id:input.requirementId},data}):db.visaDocumentRequirement.create({data})}
export async function publishChecklistDraft(id:string){const draft=await db.visaDocumentRequirement.findUnique({where:{id}});if(!draft)throw apiError('RESOURCE_NOT_FOUND','Checklist draft not found.',404);return db.$transaction(async tx=>{const requirement=await tx.visaDocumentRequirement.update({where:{id},data:{requirementStatus:'PUBLISHED'}});const published=await tx.visaDocumentRequirement.findMany({where:{visaProductId:draft.visaProductId,requirementStatus:'PUBLISHED'},orderBy:{displayOrder:'asc'}});await tx.visaProduct.update({where:{id:draft.visaProductId},data:{documents:published.map(item=>item.documentName)}});return requirement})}
